// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/(auth)/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../src/app/(auth)/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(platform)/aanvragen/[id]/[tab]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/aanvragen/[id]/[tab]">> = Specific
  const handler = {} as typeof import("../../src/app/(platform)/aanvragen/[id]/[tab]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(platform)/aanvragen/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/aanvragen/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/(platform)/aanvragen/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(platform)/aanvragen/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/aanvragen">> = Specific
  const handler = {} as typeof import("../../src/app/(platform)/aanvragen/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(platform)/account/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/account">> = Specific
  const handler = {} as typeof import("../../src/app/(platform)/account/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(platform)/afgesloten/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/afgesloten">> = Specific
  const handler = {} as typeof import("../../src/app/(platform)/afgesloten/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(platform)/bibliotheek/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/bibliotheek">> = Specific
  const handler = {} as typeof import("../../src/app/(platform)/bibliotheek/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(platform)/bronnen/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/bronnen">> = Specific
  const handler = {} as typeof import("../../src/app/(platform)/bronnen/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(platform)/everts-calc/bibliotheek/behandelingen/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/everts-calc/bibliotheek/behandelingen">> = Specific
  const handler = {} as typeof import("../../src/app/(platform)/everts-calc/bibliotheek/behandelingen/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(platform)/everts-calc/bibliotheek/materialen/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/everts-calc/bibliotheek/materialen">> = Specific
  const handler = {} as typeof import("../../src/app/(platform)/everts-calc/bibliotheek/materialen/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(platform)/everts-calc/bibliotheek/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/everts-calc/bibliotheek">> = Specific
  const handler = {} as typeof import("../../src/app/(platform)/everts-calc/bibliotheek/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(platform)/everts-calc/bibliotheek/recepten/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/everts-calc/bibliotheek/recepten">> = Specific
  const handler = {} as typeof import("../../src/app/(platform)/everts-calc/bibliotheek/recepten/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(platform)/everts-calc/bibliotheek/schilderwerk/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/everts-calc/bibliotheek/schilderwerk">> = Specific
  const handler = {} as typeof import("../../src/app/(platform)/everts-calc/bibliotheek/schilderwerk/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(platform)/everts-calc/calculaties/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/everts-calc/calculaties">> = Specific
  const handler = {} as typeof import("../../src/app/(platform)/everts-calc/calculaties/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(platform)/everts-calc/instellingen/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/everts-calc/instellingen">> = Specific
  const handler = {} as typeof import("../../src/app/(platform)/everts-calc/instellingen/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(platform)/everts-calc/meetstaat/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/everts-calc/meetstaat/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/(platform)/everts-calc/meetstaat/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(platform)/everts-calc/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/everts-calc">> = Specific
  const handler = {} as typeof import("../../src/app/(platform)/everts-calc/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(platform)/everts-calc/quotes/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/everts-calc/quotes/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/(platform)/everts-calc/quotes/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(platform)/everts-calc/quotes/[id]/preview/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/everts-calc/quotes/[id]/preview">> = Specific
  const handler = {} as typeof import("../../src/app/(platform)/everts-calc/quotes/[id]/preview/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(platform)/everts-calc/quotes/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/everts-calc/quotes/new">> = Specific
  const handler = {} as typeof import("../../src/app/(platform)/everts-calc/quotes/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(platform)/everts-calc/quotes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/everts-calc/quotes">> = Specific
  const handler = {} as typeof import("../../src/app/(platform)/everts-calc/quotes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(platform)/facturen/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/facturen">> = Specific
  const handler = {} as typeof import("../../src/app/(platform)/facturen/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(platform)/formulieren/[id]/bewerken/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/formulieren/[id]/bewerken">> = Specific
  const handler = {} as typeof import("../../src/app/(platform)/formulieren/[id]/bewerken/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(platform)/formulieren/[id]/invullen/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/formulieren/[id]/invullen">> = Specific
  const handler = {} as typeof import("../../src/app/(platform)/formulieren/[id]/invullen/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(platform)/formulieren/[id]/inzendingen/[subId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/formulieren/[id]/inzendingen/[subId]">> = Specific
  const handler = {} as typeof import("../../src/app/(platform)/formulieren/[id]/inzendingen/[subId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(platform)/formulieren/[id]/inzendingen/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/formulieren/[id]/inzendingen">> = Specific
  const handler = {} as typeof import("../../src/app/(platform)/formulieren/[id]/inzendingen/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(platform)/formulieren/nieuw/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/formulieren/nieuw">> = Specific
  const handler = {} as typeof import("../../src/app/(platform)/formulieren/nieuw/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(platform)/formulieren/overzicht/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/formulieren/overzicht">> = Specific
  const handler = {} as typeof import("../../src/app/(platform)/formulieren/overzicht/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(platform)/formulieren/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/formulieren">> = Specific
  const handler = {} as typeof import("../../src/app/(platform)/formulieren/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(platform)/formulieren/sjablonen/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/formulieren/sjablonen">> = Specific
  const handler = {} as typeof import("../../src/app/(platform)/formulieren/sjablonen/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(platform)/inkoop/facturen/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/inkoop/facturen">> = Specific
  const handler = {} as typeof import("../../src/app/(platform)/inkoop/facturen/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(platform)/instellingen/algemene-voorwaarden/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/instellingen/algemene-voorwaarden">> = Specific
  const handler = {} as typeof import("../../src/app/(platform)/instellingen/algemene-voorwaarden/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(platform)/instellingen/bedrijfsgegevens/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/instellingen/bedrijfsgegevens/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/(platform)/instellingen/bedrijfsgegevens/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(platform)/instellingen/bedrijfsgegevens/huisstijl/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/instellingen/bedrijfsgegevens/huisstijl">> = Specific
  const handler = {} as typeof import("../../src/app/(platform)/instellingen/bedrijfsgegevens/huisstijl/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(platform)/instellingen/bedrijfsgegevens/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/instellingen/bedrijfsgegevens">> = Specific
  const handler = {} as typeof import("../../src/app/(platform)/instellingen/bedrijfsgegevens/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(platform)/instellingen/betalingscondities/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/instellingen/betalingscondities">> = Specific
  const handler = {} as typeof import("../../src/app/(platform)/instellingen/betalingscondities/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(platform)/instellingen/btw-kostensoorten/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/instellingen/btw-kostensoorten">> = Specific
  const handler = {} as typeof import("../../src/app/(platform)/instellingen/btw-kostensoorten/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(platform)/instellingen/btw-tarieven/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/instellingen/btw-tarieven">> = Specific
  const handler = {} as typeof import("../../src/app/(platform)/instellingen/btw-tarieven/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(platform)/instellingen/cao/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/instellingen/cao">> = Specific
  const handler = {} as typeof import("../../src/app/(platform)/instellingen/cao/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(platform)/instellingen/debiteur-redencodes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/instellingen/debiteur-redencodes">> = Specific
  const handler = {} as typeof import("../../src/app/(platform)/instellingen/debiteur-redencodes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(platform)/instellingen/document-sjablonen/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/instellingen/document-sjablonen/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/(platform)/instellingen/document-sjablonen/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(platform)/instellingen/document-sjablonen/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/instellingen/document-sjablonen">> = Specific
  const handler = {} as typeof import("../../src/app/(platform)/instellingen/document-sjablonen/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(platform)/instellingen/dossier-categorieen/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/instellingen/dossier-categorieen">> = Specific
  const handler = {} as typeof import("../../src/app/(platform)/instellingen/dossier-categorieen/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(platform)/instellingen/dossier-toggles/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/instellingen/dossier-toggles">> = Specific
  const handler = {} as typeof import("../../src/app/(platform)/instellingen/dossier-toggles/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(platform)/instellingen/dossiermap/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/instellingen/dossiermap">> = Specific
  const handler = {} as typeof import("../../src/app/(platform)/instellingen/dossiermap/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(platform)/instellingen/dossiers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/instellingen/dossiers">> = Specific
  const handler = {} as typeof import("../../src/app/(platform)/instellingen/dossiers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(platform)/instellingen/facturatie/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/instellingen/facturatie">> = Specific
  const handler = {} as typeof import("../../src/app/(platform)/instellingen/facturatie/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(platform)/instellingen/formulieren-pdf/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/instellingen/formulieren-pdf">> = Specific
  const handler = {} as typeof import("../../src/app/(platform)/instellingen/formulieren-pdf/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(platform)/instellingen/foutenlog/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/instellingen/foutenlog">> = Specific
  const handler = {} as typeof import("../../src/app/(platform)/instellingen/foutenlog/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(platform)/instellingen/functies-afdelingen/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/instellingen/functies-afdelingen">> = Specific
  const handler = {} as typeof import("../../src/app/(platform)/instellingen/functies-afdelingen/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(platform)/instellingen/gebruikers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/instellingen/gebruikers">> = Specific
  const handler = {} as typeof import("../../src/app/(platform)/instellingen/gebruikers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(platform)/instellingen/handboek/[sectieId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/instellingen/handboek/[sectieId]">> = Specific
  const handler = {} as typeof import("../../src/app/(platform)/instellingen/handboek/[sectieId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(platform)/instellingen/handboek/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/instellingen/handboek">> = Specific
  const handler = {} as typeof import("../../src/app/(platform)/instellingen/handboek/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(platform)/instellingen/integraties/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/instellingen/integraties">> = Specific
  const handler = {} as typeof import("../../src/app/(platform)/instellingen/integraties/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(platform)/instellingen/klantportaal/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/instellingen/klantportaal">> = Specific
  const handler = {} as typeof import("../../src/app/(platform)/instellingen/klantportaal/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(platform)/instellingen/kostensoorten/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/instellingen/kostensoorten">> = Specific
  const handler = {} as typeof import("../../src/app/(platform)/instellingen/kostensoorten/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(platform)/instellingen/mailintake/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/instellingen/mailintake">> = Specific
  const handler = {} as typeof import("../../src/app/(platform)/instellingen/mailintake/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(platform)/instellingen/mailsjablonen/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/instellingen/mailsjablonen">> = Specific
  const handler = {} as typeof import("../../src/app/(platform)/instellingen/mailsjablonen/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(platform)/instellingen/medewerker-attributen/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/instellingen/medewerker-attributen">> = Specific
  const handler = {} as typeof import("../../src/app/(platform)/instellingen/medewerker-attributen/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(platform)/instellingen/medewerkers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/instellingen/medewerkers">> = Specific
  const handler = {} as typeof import("../../src/app/(platform)/instellingen/medewerkers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(platform)/instellingen/offerte-layout/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/instellingen/offerte-layout/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/(platform)/instellingen/offerte-layout/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(platform)/instellingen/offerte-layout/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/instellingen/offerte-layout">> = Specific
  const handler = {} as typeof import("../../src/app/(platform)/instellingen/offerte-layout/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(platform)/instellingen/offerte-mail/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/instellingen/offerte-mail">> = Specific
  const handler = {} as typeof import("../../src/app/(platform)/instellingen/offerte-mail/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(platform)/instellingen/offertes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/instellingen/offertes">> = Specific
  const handler = {} as typeof import("../../src/app/(platform)/instellingen/offertes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(platform)/instellingen/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/instellingen">> = Specific
  const handler = {} as typeof import("../../src/app/(platform)/instellingen/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(platform)/instellingen/planning/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/instellingen/planning">> = Specific
  const handler = {} as typeof import("../../src/app/(platform)/instellingen/planning/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(platform)/instellingen/uren/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/instellingen/uren">> = Specific
  const handler = {} as typeof import("../../src/app/(platform)/instellingen/uren/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(platform)/instellingen/uursoorten-tarieven/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/instellingen/uursoorten-tarieven">> = Specific
  const handler = {} as typeof import("../../src/app/(platform)/instellingen/uursoorten-tarieven/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(platform)/kam/formulieren/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/kam/formulieren">> = Specific
  const handler = {} as typeof import("../../src/app/(platform)/kam/formulieren/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(platform)/kam/kwaliteit/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/kam/kwaliteit/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/(platform)/kam/kwaliteit/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(platform)/kam/kwaliteit/afwijkingen/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/kam/kwaliteit/afwijkingen">> = Specific
  const handler = {} as typeof import("../../src/app/(platform)/kam/kwaliteit/afwijkingen/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(platform)/kam/kwaliteit/bibliotheek/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/kam/kwaliteit/bibliotheek">> = Specific
  const handler = {} as typeof import("../../src/app/(platform)/kam/kwaliteit/bibliotheek/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(platform)/kam/kwaliteit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/kam/kwaliteit">> = Specific
  const handler = {} as typeof import("../../src/app/(platform)/kam/kwaliteit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(platform)/kam/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/kam">> = Specific
  const handler = {} as typeof import("../../src/app/(platform)/kam/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(platform)/kam/toolbox/[id]/bewerken/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/kam/toolbox/[id]/bewerken">> = Specific
  const handler = {} as typeof import("../../src/app/(platform)/kam/toolbox/[id]/bewerken/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(platform)/kam/toolbox/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/kam/toolbox/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/(platform)/kam/toolbox/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(platform)/kam/toolbox/[id]/presenteren/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/kam/toolbox/[id]/presenteren">> = Specific
  const handler = {} as typeof import("../../src/app/(platform)/kam/toolbox/[id]/presenteren/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(platform)/kam/toolbox/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/kam/toolbox">> = Specific
  const handler = {} as typeof import("../../src/app/(platform)/kam/toolbox/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(platform)/kam/vca-diplomas/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/kam/vca-diplomas">> = Specific
  const handler = {} as typeof import("../../src/app/(platform)/kam/vca-diplomas/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(platform)/mailintake/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/mailintake/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/(platform)/mailintake/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(platform)/mailintake/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/mailintake">> = Specific
  const handler = {} as typeof import("../../src/app/(platform)/mailintake/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(platform)/management/(views)/calculators/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/management/calculators">> = Specific
  const handler = {} as typeof import("../../src/app/(platform)/management/(views)/calculators/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(platform)/management/(views)/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/management/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/(platform)/management/(views)/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(platform)/management/(views)/gereed/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/management/gereed">> = Specific
  const handler = {} as typeof import("../../src/app/(platform)/management/(views)/gereed/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(platform)/management/(views)/historie/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/management/historie">> = Specific
  const handler = {} as typeof import("../../src/app/(platform)/management/(views)/historie/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(platform)/management/(views)/lopend/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/management/lopend">> = Specific
  const handler = {} as typeof import("../../src/app/(platform)/management/(views)/lopend/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(platform)/management/(views)/servicedesk/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/management/servicedesk">> = Specific
  const handler = {} as typeof import("../../src/app/(platform)/management/(views)/servicedesk/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(platform)/management/(views)/verkoop/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/management/verkoop">> = Specific
  const handler = {} as typeof import("../../src/app/(platform)/management/(views)/verkoop/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(platform)/management/(views)/werkvoorraad/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/management/werkvoorraad">> = Specific
  const handler = {} as typeof import("../../src/app/(platform)/management/(views)/werkvoorraad/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(platform)/management/instellingen/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/management/instellingen">> = Specific
  const handler = {} as typeof import("../../src/app/(platform)/management/instellingen/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(platform)/management/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/management">> = Specific
  const handler = {} as typeof import("../../src/app/(platform)/management/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(platform)/materieelbeheer/[id]/bewerken/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/materieelbeheer/[id]/bewerken">> = Specific
  const handler = {} as typeof import("../../src/app/(platform)/materieelbeheer/[id]/bewerken/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(platform)/materieelbeheer/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/materieelbeheer/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/(platform)/materieelbeheer/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(platform)/materieelbeheer/controle/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/materieelbeheer/controle">> = Specific
  const handler = {} as typeof import("../../src/app/(platform)/materieelbeheer/controle/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(platform)/materieelbeheer/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/materieelbeheer/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/(platform)/materieelbeheer/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(platform)/materieelbeheer/factuur-import/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/materieelbeheer/factuur-import">> = Specific
  const handler = {} as typeof import("../../src/app/(platform)/materieelbeheer/factuur-import/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(platform)/materieelbeheer/instellingen/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/materieelbeheer/instellingen">> = Specific
  const handler = {} as typeof import("../../src/app/(platform)/materieelbeheer/instellingen/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(platform)/materieelbeheer/nieuw/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/materieelbeheer/nieuw">> = Specific
  const handler = {} as typeof import("../../src/app/(platform)/materieelbeheer/nieuw/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(platform)/materieelbeheer/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/materieelbeheer">> = Specific
  const handler = {} as typeof import("../../src/app/(platform)/materieelbeheer/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(platform)/medewerkers/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/medewerkers/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/(platform)/medewerkers/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(platform)/medewerkers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/medewerkers">> = Specific
  const handler = {} as typeof import("../../src/app/(platform)/medewerkers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(platform)/mijn-taken/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/mijn-taken">> = Specific
  const handler = {} as typeof import("../../src/app/(platform)/mijn-taken/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(platform)/objecten/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/objecten/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/(platform)/objecten/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(platform)/objecten/nieuw/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/objecten/nieuw">> = Specific
  const handler = {} as typeof import("../../src/app/(platform)/objecten/nieuw/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(platform)/objecten/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/objecten">> = Specific
  const handler = {} as typeof import("../../src/app/(platform)/objecten/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(platform)/offertes/[id]/[tab]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/offertes/[id]/[tab]">> = Specific
  const handler = {} as typeof import("../../src/app/(platform)/offertes/[id]/[tab]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(platform)/offertes/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/offertes/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/(platform)/offertes/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(platform)/offertes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/offertes">> = Specific
  const handler = {} as typeof import("../../src/app/(platform)/offertes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(platform)/opdrachten/[id]/[tab]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/opdrachten/[id]/[tab]">> = Specific
  const handler = {} as typeof import("../../src/app/(platform)/opdrachten/[id]/[tab]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(platform)/opdrachten/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/opdrachten/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/(platform)/opdrachten/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(platform)/opdrachten/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/opdrachten">> = Specific
  const handler = {} as typeof import("../../src/app/(platform)/opdrachten/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(platform)/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/(platform)/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(platform)/planning/bedrijfsagenda/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/planning/bedrijfsagenda">> = Specific
  const handler = {} as typeof import("../../src/app/(platform)/planning/bedrijfsagenda/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(platform)/planning/medewerker/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/planning/medewerker">> = Specific
  const handler = {} as typeof import("../../src/app/(platform)/planning/medewerker/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(platform)/planning/mijn-werkbonnen/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/planning/mijn-werkbonnen">> = Specific
  const handler = {} as typeof import("../../src/app/(platform)/planning/mijn-werkbonnen/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(platform)/planning/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/planning">> = Specific
  const handler = {} as typeof import("../../src/app/(platform)/planning/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(platform)/planning/project/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/planning/project">> = Specific
  const handler = {} as typeof import("../../src/app/(platform)/planning/project/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(platform)/planning/werkbon/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/planning/werkbon/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/(platform)/planning/werkbon/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(platform)/relaties/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/relaties/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/(platform)/relaties/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(platform)/relaties/contactpersonen/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/relaties/contactpersonen/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/(platform)/relaties/contactpersonen/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(platform)/relaties/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/relaties">> = Specific
  const handler = {} as typeof import("../../src/app/(platform)/relaties/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(platform)/relaties/particulieren/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/relaties/particulieren/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/(platform)/relaties/particulieren/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(platform)/servicedesk/[id]/[tab]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/servicedesk/[id]/[tab]">> = Specific
  const handler = {} as typeof import("../../src/app/(platform)/servicedesk/[id]/[tab]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(platform)/servicedesk/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/servicedesk/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/(platform)/servicedesk/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(platform)/servicedesk/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/servicedesk">> = Specific
  const handler = {} as typeof import("../../src/app/(platform)/servicedesk/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(platform)/taken/lijsten/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/taken/lijsten/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/(platform)/taken/lijsten/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(platform)/taken/lijsten/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/taken/lijsten">> = Specific
  const handler = {} as typeof import("../../src/app/(platform)/taken/lijsten/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(platform)/taken/overzicht/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/taken/overzicht">> = Specific
  const handler = {} as typeof import("../../src/app/(platform)/taken/overzicht/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(platform)/taken/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/taken">> = Specific
  const handler = {} as typeof import("../../src/app/(platform)/taken/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(platform)/uren/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/uren">> = Specific
  const handler = {} as typeof import("../../src/app/(platform)/uren/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(platform)/vraag-eva/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/vraag-eva">> = Specific
  const handler = {} as typeof import("../../src/app/(platform)/vraag-eva/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(platform)/wagenpark/bestuurders/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/wagenpark/bestuurders/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/(platform)/wagenpark/bestuurders/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(platform)/wagenpark/bestuurders/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/wagenpark/bestuurders">> = Specific
  const handler = {} as typeof import("../../src/app/(platform)/wagenpark/bestuurders/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(platform)/wagenpark/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/wagenpark/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/(platform)/wagenpark/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(platform)/wagenpark/diagnose/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/wagenpark/diagnose">> = Specific
  const handler = {} as typeof import("../../src/app/(platform)/wagenpark/diagnose/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(platform)/wagenpark/instellingen/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/wagenpark/instellingen">> = Specific
  const handler = {} as typeof import("../../src/app/(platform)/wagenpark/instellingen/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(platform)/wagenpark/leasecontracten/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/wagenpark/leasecontracten">> = Specific
  const handler = {} as typeof import("../../src/app/(platform)/wagenpark/leasecontracten/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(platform)/wagenpark/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/wagenpark">> = Specific
  const handler = {} as typeof import("../../src/app/(platform)/wagenpark/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(platform)/wagenpark/parkeren/import/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/wagenpark/parkeren/import">> = Specific
  const handler = {} as typeof import("../../src/app/(platform)/wagenpark/parkeren/import/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(platform)/wagenpark/parkeren/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/wagenpark/parkeren">> = Specific
  const handler = {} as typeof import("../../src/app/(platform)/wagenpark/parkeren/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(platform)/wagenpark/parkeren/toewijzen/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/wagenpark/parkeren/toewijzen">> = Specific
  const handler = {} as typeof import("../../src/app/(platform)/wagenpark/parkeren/toewijzen/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(platform)/wagenpark/parkeren/zones/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/wagenpark/parkeren/zones">> = Specific
  const handler = {} as typeof import("../../src/app/(platform)/wagenpark/parkeren/zones/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(platform)/wagenpark/ritten/import/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/wagenpark/ritten/import">> = Specific
  const handler = {} as typeof import("../../src/app/(platform)/wagenpark/ritten/import/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(platform)/wagenpark/ritten/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/wagenpark/ritten">> = Specific
  const handler = {} as typeof import("../../src/app/(platform)/wagenpark/ritten/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(platform)/wagenpark/ritten/sync/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/wagenpark/ritten/sync">> = Specific
  const handler = {} as typeof import("../../src/app/(platform)/wagenpark/ritten/sync/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(platform)/wagenpark/voertuigen/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/wagenpark/voertuigen/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/(platform)/wagenpark/voertuigen/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(platform)/wagenpark/voertuigen/nieuw/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/wagenpark/voertuigen/nieuw">> = Specific
  const handler = {} as typeof import("../../src/app/(platform)/wagenpark/voertuigen/nieuw/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(platform)/wagenpark/voertuigen/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/wagenpark/voertuigen">> = Specific
  const handler = {} as typeof import("../../src/app/(platform)/wagenpark/voertuigen/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(platform)/wat-is-nieuw/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/wat-is-nieuw">> = Specific
  const handler = {} as typeof import("../../src/app/(platform)/wat-is-nieuw/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(portaal)/portaal/geen-toegang/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/portaal/geen-toegang">> = Specific
  const handler = {} as typeof import("../../src/app/(portaal)/portaal/geen-toegang/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(portaal)/portaal/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/portaal/login">> = Specific
  const handler = {} as typeof import("../../src/app/(portaal)/portaal/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(portaal)/portaal/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/portaal">> = Specific
  const handler = {} as typeof import("../../src/app/(portaal)/portaal/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(portaal)/portaal/project/[id]/berichten/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/portaal/project/[id]/berichten">> = Specific
  const handler = {} as typeof import("../../src/app/(portaal)/portaal/project/[id]/berichten/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(portaal)/portaal/project/[id]/documenten/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/portaal/project/[id]/documenten">> = Specific
  const handler = {} as typeof import("../../src/app/(portaal)/portaal/project/[id]/documenten/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(portaal)/portaal/project/[id]/facturen/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/portaal/project/[id]/facturen">> = Specific
  const handler = {} as typeof import("../../src/app/(portaal)/portaal/project/[id]/facturen/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(portaal)/portaal/project/[id]/formulieren/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/portaal/project/[id]/formulieren">> = Specific
  const handler = {} as typeof import("../../src/app/(portaal)/portaal/project/[id]/formulieren/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(portaal)/portaal/project/[id]/fotos/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/portaal/project/[id]/fotos">> = Specific
  const handler = {} as typeof import("../../src/app/(portaal)/portaal/project/[id]/fotos/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(portaal)/portaal/project/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/portaal/project/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/(portaal)/portaal/project/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(public)/p/akkoord/[token]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/p/akkoord/[token]">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/p/akkoord/[token]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(public)/p/feedback/[token]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/p/feedback/[token]">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/p/feedback/[token]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(public)/p/oplevering/[token]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/p/oplevering/[token]">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/p/oplevering/[token]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/auth/ds-preview/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/ds-preview">> = Specific
  const handler = {} as typeof import("../../src/app/auth/ds-preview/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/auth/mailintake-preview/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/mailintake-preview">> = Specific
  const handler = {} as typeof import("../../src/app/auth/mailintake-preview/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/auth/ui-preview/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/ui-preview">> = Specific
  const handler = {} as typeof import("../../src/app/auth/ui-preview/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/auth/verkoop-proef/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/verkoop-proef">> = Specific
  const handler = {} as typeof import("../../src/app/auth/verkoop-proef/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/m/bezoek/[bezoekId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/m/bezoek/[bezoekId]">> = Specific
  const handler = {} as typeof import("../../src/app/m/bezoek/[bezoekId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/m/commercieel/[relatieId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/m/commercieel/[relatieId]">> = Specific
  const handler = {} as typeof import("../../src/app/m/commercieel/[relatieId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/m/commercieel/cp/[contactpersoonId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/m/commercieel/cp/[contactpersoonId]">> = Specific
  const handler = {} as typeof import("../../src/app/m/commercieel/cp/[contactpersoonId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/m/commercieel/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/m/commercieel">> = Specific
  const handler = {} as typeof import("../../src/app/m/commercieel/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/m/dossiers/[id]/[tab]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/m/dossiers/[id]/[tab]">> = Specific
  const handler = {} as typeof import("../../src/app/m/dossiers/[id]/[tab]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/m/dossiers/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/m/dossiers/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/m/dossiers/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/m/dossiers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/m/dossiers">> = Specific
  const handler = {} as typeof import("../../src/app/m/dossiers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/m/handboek/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/m/handboek/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/m/handboek/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/m/handboek/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/m/handboek">> = Specific
  const handler = {} as typeof import("../../src/app/m/handboek/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/m/handboek/situatie/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/m/handboek/situatie/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/m/handboek/situatie/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/m/kwaliteit/[inspectieId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/m/kwaliteit/[inspectieId]">> = Specific
  const handler = {} as typeof import("../../src/app/m/kwaliteit/[inspectieId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/m/materieel/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/m/materieel/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/m/materieel/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/m/materieel/koppel/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/m/materieel/koppel">> = Specific
  const handler = {} as typeof import("../../src/app/m/materieel/koppel/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/m/materieel/nieuw/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/m/materieel/nieuw">> = Specific
  const handler = {} as typeof import("../../src/app/m/materieel/nieuw/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/m/materieel/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/m/materieel">> = Specific
  const handler = {} as typeof import("../../src/app/m/materieel/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/m/materieel/scan/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/m/materieel/scan">> = Specific
  const handler = {} as typeof import("../../src/app/m/materieel/scan/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/m/notificaties/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/m/notificaties">> = Specific
  const handler = {} as typeof import("../../src/app/m/notificaties/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/m/oplevering/[momentId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/m/oplevering/[momentId]">> = Specific
  const handler = {} as typeof import("../../src/app/m/oplevering/[momentId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/m/opname/[opnameId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/m/opname/[opnameId]">> = Specific
  const handler = {} as typeof import("../../src/app/m/opname/[opnameId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/m/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/m">> = Specific
  const handler = {} as typeof import("../../src/app/m/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/m/planning/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/m/planning">> = Specific
  const handler = {} as typeof import("../../src/app/m/planning/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/m/prikklok/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/m/prikklok">> = Specific
  const handler = {} as typeof import("../../src/app/m/prikklok/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/m/prikklok/week/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/m/prikklok/week">> = Specific
  const handler = {} as typeof import("../../src/app/m/prikklok/week/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/m/profiel/instellingen/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/m/profiel/instellingen">> = Specific
  const handler = {} as typeof import("../../src/app/m/profiel/instellingen/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/m/profiel/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/m/profiel">> = Specific
  const handler = {} as typeof import("../../src/app/m/profiel/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/m/taken/[taakId]/bezoek/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/m/taken/[taakId]/bezoek">> = Specific
  const handler = {} as typeof import("../../src/app/m/taken/[taakId]/bezoek/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/m/taken/[taakId]/formulier/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/m/taken/[taakId]/formulier">> = Specific
  const handler = {} as typeof import("../../src/app/m/taken/[taakId]/formulier/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/m/taken/[taakId]/opname/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/m/taken/[taakId]/opname">> = Specific
  const handler = {} as typeof import("../../src/app/m/taken/[taakId]/opname/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/m/taken/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/m/taken">> = Specific
  const handler = {} as typeof import("../../src/app/m/taken/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/m/toolbox/[toewijzingId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/m/toolbox/[toewijzingId]">> = Specific
  const handler = {} as typeof import("../../src/app/m/toolbox/[toewijzingId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/m/uren/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/m/uren/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/m/uren/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/m/uren/keuren/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/m/uren/keuren">> = Specific
  const handler = {} as typeof import("../../src/app/m/uren/keuren/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/m/uren/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/m/uren">> = Specific
  const handler = {} as typeof import("../../src/app/m/uren/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/m/verlof/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/m/verlof">> = Specific
  const handler = {} as typeof import("../../src/app/m/verlof/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/wachtwoord-instellen/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/wachtwoord-instellen">> = Specific
  const handler = {} as typeof import("../../src/app/wachtwoord-instellen/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(platform)/api/documenten/pdf/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/documenten/pdf">> = Specific
  const handler = {} as typeof import("../../src/app/(platform)/api/documenten/pdf/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(platform)/api/documenten/preview/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/documenten/preview">> = Specific
  const handler = {} as typeof import("../../src/app/(platform)/api/documenten/preview/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(platform)/api/documenten/word-online/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/documenten/word-online">> = Specific
  const handler = {} as typeof import("../../src/app/(platform)/api/documenten/word-online/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(platform)/api/eva/ask/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/eva/ask">> = Specific
  const handler = {} as typeof import("../../src/app/(platform)/api/eva/ask/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(platform)/api/eva/medewerker/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/eva/medewerker">> = Specific
  const handler = {} as typeof import("../../src/app/(platform)/api/eva/medewerker/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(platform)/api/eva/search/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/eva/search">> = Specific
  const handler = {} as typeof import("../../src/app/(platform)/api/eva/search/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(platform)/everts-calc/api/bibliotheek/sjabloon/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/everts-calc/api/bibliotheek/sjabloon">> = Specific
  const handler = {} as typeof import("../../src/app/(platform)/everts-calc/api/bibliotheek/sjabloon/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(platform)/everts-calc/api/briefpapier/upload/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/everts-calc/api/briefpapier/upload">> = Specific
  const handler = {} as typeof import("../../src/app/(platform)/everts-calc/api/briefpapier/upload/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(platform)/everts-calc/api/docx-templates/graph/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/everts-calc/api/docx-templates/graph">> = Specific
  const handler = {} as typeof import("../../src/app/(platform)/everts-calc/api/docx-templates/graph/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(platform)/everts-calc/api/docx-templates/upload/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/everts-calc/api/docx-templates/upload">> = Specific
  const handler = {} as typeof import("../../src/app/(platform)/everts-calc/api/docx-templates/upload/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(platform)/everts-calc/api/docx-templates/valideer/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/everts-calc/api/docx-templates/valideer">> = Specific
  const handler = {} as typeof import("../../src/app/(platform)/everts-calc/api/docx-templates/valideer/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(platform)/everts-calc/api/materialen/dico/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/everts-calc/api/materialen/dico">> = Specific
  const handler = {} as typeof import("../../src/app/(platform)/everts-calc/api/materialen/dico/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(platform)/everts-calc/api/materialen/sjabloon/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/everts-calc/api/materialen/sjabloon">> = Specific
  const handler = {} as typeof import("../../src/app/(platform)/everts-calc/api/materialen/sjabloon/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(platform)/everts-calc/api/o365/diagnose/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/everts-calc/api/o365/diagnose">> = Specific
  const handler = {} as typeof import("../../src/app/(platform)/everts-calc/api/o365/diagnose/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(platform)/everts-calc/api/opname/sjabloon/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/everts-calc/api/opname/sjabloon">> = Specific
  const handler = {} as typeof import("../../src/app/(platform)/everts-calc/api/opname/sjabloon/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(platform)/everts-calc/api/quotes/[id]/docx-preview/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/everts-calc/api/quotes/[id]/docx-preview">> = Specific
  const handler = {} as typeof import("../../src/app/(platform)/everts-calc/api/quotes/[id]/docx-preview/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(platform)/everts-calc/api/quotes/[id]/docx/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/everts-calc/api/quotes/[id]/docx">> = Specific
  const handler = {} as typeof import("../../src/app/(platform)/everts-calc/api/quotes/[id]/docx/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(platform)/everts-calc/api/quotes/[id]/pdf-preview/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/everts-calc/api/quotes/[id]/pdf-preview">> = Specific
  const handler = {} as typeof import("../../src/app/(platform)/everts-calc/api/quotes/[id]/pdf-preview/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(platform)/everts-calc/api/quotes/[id]/pdf/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/everts-calc/api/quotes/[id]/pdf">> = Specific
  const handler = {} as typeof import("../../src/app/(platform)/everts-calc/api/quotes/[id]/pdf/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(platform)/everts-calc/api/quotes/[id]/word-online/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/everts-calc/api/quotes/[id]/word-online">> = Specific
  const handler = {} as typeof import("../../src/app/(platform)/everts-calc/api/quotes/[id]/word-online/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(platform)/everts-calc/api/schilderwerk/sjabloon/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/everts-calc/api/schilderwerk/sjabloon">> = Specific
  const handler = {} as typeof import("../../src/app/(platform)/everts-calc/api/schilderwerk/sjabloon/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(platform)/formulieren/[id]/inzendingen/[subId]/pdf/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/formulieren/[id]/inzendingen/[subId]/pdf">> = Specific
  const handler = {} as typeof import("../../src/app/(platform)/formulieren/[id]/inzendingen/[subId]/pdf/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(platform)/formulieren/[id]/preview-pdf/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/formulieren/[id]/preview-pdf">> = Specific
  const handler = {} as typeof import("../../src/app/(platform)/formulieren/[id]/preview-pdf/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(platform)/kam/toolbox/[id]/presentielijst/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/kam/toolbox/[id]/presentielijst">> = Specific
  const handler = {} as typeof import("../../src/app/(platform)/kam/toolbox/[id]/presentielijst/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(platform)/wagenpark/bestuurders/[id]/werktijden/pdf/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/wagenpark/bestuurders/[id]/werktijden/pdf">> = Specific
  const handler = {} as typeof import("../../src/app/(platform)/wagenpark/bestuurders/[id]/werktijden/pdf/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(portaal)/portaal/auth/callback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/portaal/auth/callback">> = Specific
  const handler = {} as typeof import("../../src/app/(portaal)/portaal/auth/callback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/o365/callback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/o365/callback">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/o365/callback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/o365/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/o365">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/o365/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/bouw7/bestand/[hash]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/bouw7/bestand/[hash]">> = Specific
  const handler = {} as typeof import("../../src/app/api/bouw7/bestand/[hash]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/cron/bouw7-snapshots/[mode]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/bouw7-snapshots/[mode]">> = Specific
  const handler = {} as typeof import("../../src/app/api/cron/bouw7-snapshots/[mode]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/cron/bouw7-sync/[mode]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/bouw7-sync/[mode]">> = Specific
  const handler = {} as typeof import("../../src/app/api/cron/bouw7-sync/[mode]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/cron/bouw7-sync/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/bouw7-sync">> = Specific
  const handler = {} as typeof import("../../src/app/api/cron/bouw7-sync/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/cron/dagsignalen/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/dagsignalen">> = Specific
  const handler = {} as typeof import("../../src/app/api/cron/dagsignalen/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/cron/fouten-opruimen/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/fouten-opruimen">> = Specific
  const handler = {} as typeof import("../../src/app/api/cron/fouten-opruimen/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/cron/mailintake/bewaking/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/mailintake/bewaking">> = Specific
  const handler = {} as typeof import("../../src/app/api/cron/mailintake/bewaking/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/cron/mailintake/ophalen/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/mailintake/ophalen">> = Specific
  const handler = {} as typeof import("../../src/app/api/cron/mailintake/ophalen/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/cron/mailintake/verwerken/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/mailintake/verwerken">> = Specific
  const handler = {} as typeof import("../../src/app/api/cron/mailintake/verwerken/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/cron/oplevering/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/oplevering">> = Specific
  const handler = {} as typeof import("../../src/app/api/cron/oplevering/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/cron/parkeren-toewijzing/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/parkeren-toewijzing">> = Specific
  const handler = {} as typeof import("../../src/app/api/cron/parkeren-toewijzing/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/cron/portaal-mail/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/portaal-mail">> = Specific
  const handler = {} as typeof import("../../src/app/api/cron/portaal-mail/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/cron/prikklok/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/prikklok">> = Specific
  const handler = {} as typeof import("../../src/app/api/cron/prikklok/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/cron/toolbox-momenten/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/toolbox-momenten">> = Specific
  const handler = {} as typeof import("../../src/app/api/cron/toolbox-momenten/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/cron/ulu-sync/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/ulu-sync">> = Specific
  const handler = {} as typeof import("../../src/app/api/cron/ulu-sync/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/cron/uren/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/uren">> = Specific
  const handler = {} as typeof import("../../src/app/api/cron/uren/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/cron/wagenpark-weeksamenvatting/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/wagenpark-weeksamenvatting">> = Specific
  const handler = {} as typeof import("../../src/app/api/cron/wagenpark-weeksamenvatting/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/dossier-bestand/mail/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dossier-bestand/mail">> = Specific
  const handler = {} as typeof import("../../src/app/api/dossier-bestand/mail/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/dossier-bestand/markdown/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dossier-bestand/markdown">> = Specific
  const handler = {} as typeof import("../../src/app/api/dossier-bestand/markdown/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/dossier-bestand/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dossier-bestand">> = Specific
  const handler = {} as typeof import("../../src/app/api/dossier-bestand/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/dossiers/[dossierId]/detailplanning/pdf/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dossiers/[dossierId]/detailplanning/pdf">> = Specific
  const handler = {} as typeof import("../../src/app/api/dossiers/[dossierId]/detailplanning/pdf/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/dossiers/[dossierId]/meerwerk/pdf/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dossiers/[dossierId]/meerwerk/pdf">> = Specific
  const handler = {} as typeof import("../../src/app/api/dossiers/[dossierId]/meerwerk/pdf/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/dossiers/[dossierId]/offerte/pdf/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dossiers/[dossierId]/offerte/pdf">> = Specific
  const handler = {} as typeof import("../../src/app/api/dossiers/[dossierId]/offerte/pdf/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/fouten/melden/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/fouten/melden">> = Specific
  const handler = {} as typeof import("../../src/app/api/fouten/melden/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/handboek/bijlage/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/handboek/bijlage/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/handboek/bijlage/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/handboek/pdf/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/handboek/pdf">> = Specific
  const handler = {} as typeof import("../../src/app/api/handboek/pdf/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/inkoopfacturen/[id]/document/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/inkoopfacturen/[id]/document">> = Specific
  const handler = {} as typeof import("../../src/app/api/inkoopfacturen/[id]/document/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/nieuws/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/nieuws">> = Specific
  const handler = {} as typeof import("../../src/app/api/nieuws/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/oplevering/rapport/[momentId]/pdf/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/oplevering/rapport/[momentId]/pdf">> = Specific
  const handler = {} as typeof import("../../src/app/api/oplevering/rapport/[momentId]/pdf/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/oplevering/rapport/[momentId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/oplevering/rapport/[momentId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/oplevering/rapport/[momentId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/portaal/bijlage-intern/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/portaal/bijlage-intern">> = Specific
  const handler = {} as typeof import("../../src/app/api/portaal/bijlage-intern/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/portaal/bijlage/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/portaal/bijlage">> = Specific
  const handler = {} as typeof import("../../src/app/api/portaal/bijlage/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/portaal/formulier-pdf/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/portaal/formulier-pdf">> = Specific
  const handler = {} as typeof import("../../src/app/api/portaal/formulier-pdf/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/push/aanmelden/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/push/aanmelden">> = Specific
  const handler = {} as typeof import("../../src/app/api/push/aanmelden/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/push/afmelden/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/push/afmelden">> = Specific
  const handler = {} as typeof import("../../src/app/api/push/afmelden/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/push/sleutel/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/push/sleutel">> = Specific
  const handler = {} as typeof import("../../src/app/api/push/sleutel/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/push/test/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/push/test">> = Specific
  const handler = {} as typeof import("../../src/app/api/push/test/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/weather/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/weather">> = Specific
  const handler = {} as typeof import("../../src/app/api/weather/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/auth/callback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/auth/callback">> = Specific
  const handler = {} as typeof import("../../src/app/auth/callback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/(platform)/everts-calc/calculaties/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/everts-calc/calculaties">> = Specific
  const handler = {} as typeof import("../../src/app/(platform)/everts-calc/calculaties/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(platform)/everts-calc/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/everts-calc">> = Specific
  const handler = {} as typeof import("../../src/app/(platform)/everts-calc/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(platform)/formulieren/nieuw/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/formulieren/nieuw">> = Specific
  const handler = {} as typeof import("../../src/app/(platform)/formulieren/nieuw/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(platform)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/(platform)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(platform)/management/(views)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/management">> = Specific
  const handler = {} as typeof import("../../src/app/(platform)/management/(views)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(platform)/materieelbeheer/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/materieelbeheer">> = Specific
  const handler = {} as typeof import("../../src/app/(platform)/materieelbeheer/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(platform)/planning/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/planning">> = Specific
  const handler = {} as typeof import("../../src/app/(platform)/planning/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(platform)/taken/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/taken">> = Specific
  const handler = {} as typeof import("../../src/app/(platform)/taken/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(platform)/wagenpark/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/wagenpark">> = Specific
  const handler = {} as typeof import("../../src/app/(platform)/wagenpark/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(portaal)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/(portaal)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(portaal)/portaal/project/[id]/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/portaal/project/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/(portaal)/portaal/project/[id]/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(public)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/m/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/m">> = Specific
  const handler = {} as typeof import("../../src/app/m/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
