-- Seed van de kwaliteitsbibliotheek: 22 disciplines en 167 controlepunten voor de buitenschil.
--
-- BRONCLASSIFICATIE — lees dit voordat je een waarde wijzigt.
-- Alle grenswaarden hieronder staan op bron_type = 'INTERN' met de herkomst als tekst in
-- bron_document ("Bedrijfsnorm, ontleend aan BRL 5026"). Dat is bewust: de waarden komen uit de
-- praktijkopzet van het bedrijf en zijn niet tegen de originele norm geverifieerd. Een klantrapport
-- mag daarom "interne kwaliteitseis" tonen en niet "NEN-eis". Zet een punt pas op 'NORM' zodra
-- iemand de norm daadwerkelijk heeft nageslagen en de paragraaf heeft ingevuld.
--
-- Waar de grenswaarde per systeem, fabrikant of bestek verschilt (kitvoegbreedte en -diepte,
-- glaslatbevestiging, sponninghoogte, omtrekspeling, coatingcondities, laagdikte, treksterkte
-- betonherstel, vlakheid) staat er GEEN generieke waarde. Die punten dragen een
-- project_eis_sleutel; de inspectieflow vraagt dan om de projectwaarde in plaats van een
-- verzonnen getal.
--
-- Idempotent: on conflict (code) do nothing, zodat opnieuw draaien niets overschrijft dat de
-- beheerder inmiddels in het beheerscherm heeft bijgesteld.

-- ── Disciplines ──────────────────────────────────────────────────────────────
insert into public.kwaliteit_disciplines (code, naam, groep, volgorde, altijd_aan) values
  ('ALG','Algemeen',                            'buitenschil',  10, true),
  ('SCH','Schilderwerk hout',                   'buitenschil',  20, false),
  ('HHR','Houtrotherstel',                      'buitenschil',  30, false),
  ('KOZ','Kozijnen, ramen en deuren',           'buitenschil',  40, false),
  ('GL', 'Beglazing',                           'buitenschil',  50, false),
  ('KIT','Kitwerk gevel',                       'buitenschil',  60, false),
  ('MW', 'Metselwerk',                          'buitenschil',  70, false),
  ('VW', 'Voegwerk',                            'buitenschil',  80, false),
  ('GR', 'Gevelreiniging',                      'buitenschil',  90, false),
  ('GC', 'Gevelcoating',                        'buitenschil', 100, false),
  ('BET','Betonherstel',                        'buitenschil', 110, false),
  ('STU','Gevelstuc- en pleisterwerk',          'buitenschil', 120, false),
  ('GBH','Houten gevelbekleding',               'buitenschil', 130, false),
  ('GBM','Plaat- en metalen gevelbekleding',    'buitenschil', 140, false),
  ('MET','Metaalconservering',                  'buitenschil', 150, false),
  ('DR', 'Dakranden en boeidelen',              'buitenschil', 160, false),
  ('PD', 'Plat dak',                            'buitenschil', 170, false),
  ('HD', 'Hellend dak',                         'buitenschil', 180, false),
  ('LZ', 'Lood- en zinkwerk',                   'buitenschil', 190, false),
  ('HWA','Hemelwaterafvoer',                    'buitenschil', 200, false),
  ('BAL','Balustrades en hekwerken',            'buitenschil', 210, false),
  ('EST','Esthetische eindkwaliteit',           'buitenschil', 220, false)
on conflict (code) do nothing;

-- ── A. Binaire visuele controlepunten ────────────────────────────────────────
-- Het gros van de bibliotheek. binair_voldoet_bij legt vast welk antwoord goed is; de rekenregel
-- in lib/kwaliteit/regels.ts heeft verder niets nodig.
insert into public.kwaliteit_controlepunten
  (code, discipline_code, component, titel, korte_vraag, toelichting, binair_voldoet_bij,
   kwaliteitsaspect, standaard_ernst, eis_tekst, rapport_tekst_voldoet_niet,
   standaard_herstelactie, volgorde)
values

-- ALGEMEEN --------------------------------------------------------------------
('ALG-01','ALG','Bestaand werk','Beschadiging bestaand werk',
 'Zijn door de werkzaamheden nieuwe beschadigingen aan bestaand werk zichtbaar?',
 'Kijk naar glas, kozijnen, gevel, bestrating, dak, installaties en bezittingen van bewoners.','nee',
 'technisch','technisch',
 'De werkzaamheden veroorzaken geen schade aan bestaand werk.',
 'Er zijn beschadigingen aan bestaand werk geconstateerd die door de werkzaamheden zijn ontstaan.',
 'Schade herstellen in de oorspronkelijke staat en de oorzaak wegnemen.',10),

('ALG-02','ALG','Bescherming','Bescherming bestaand werk',
 'Is bestaand werk voldoende beschermd tegen voorzienbare beschadiging door de lopende werkzaamheden?',
 'Denk aan afplakken, afdekken, afschermen van beplanting, bestrating en glas.','ja',
 'technisch','observatie',
 'Bestaand werk is afdoende beschermd tegen voorzienbare schade.',
 'De bescherming van bestaand werk is op deze locatie onvoldoende.',
 'Bescherming aanbrengen voordat de werkzaamheden worden voortgezet.',20),

('ALG-03','ALG','Netheid','Werkgerelateerde vervuiling',
 'Zijn werkgerelateerde vervuilingen aanwezig op gereed werk?',
 'Verf, kit, mortel, slijpstof, cementsluier of lijm op afgewerkte delen.','nee',
 'esthetisch','esthetisch',
 'Gereed werk is vrij van werkgerelateerde vervuiling.',
 'Op gereed werk is werkgerelateerde vervuiling aangetroffen.',
 'Vervuiling verwijderen zonder de onderliggende afwerking te beschadigen.',30),

('ALG-04','ALG','Aansluitingen','Aansluitingen tussen disciplines',
 'Zijn de zichtbare aansluitingen tussen verschillende werkzaamheden technisch gesloten en correct uitgevoerd?',
 'Let op de overgangen tussen schilderwerk, kitwerk, metselwerk, dakwerk en installaties.','ja',
 'technisch','technisch',
 'Aansluitingen tussen disciplines zijn gesloten en correct uitgevoerd.',
 'Een of meer aansluitingen tussen werkzaamheden zijn niet gesloten of niet correct uitgevoerd.',
 'Aansluiting alsnog sluiten volgens het toepasselijke detail; verantwoordelijke discipline aanwijzen.',40),

('ALG-05','ALG','Veiligheid','Losse of onveilige onderdelen',
 'Zijn losse of potentieel gevaarlijke bouwdelen aanwezig?',
 'Elk los bouwdeel is een veiligheidsrisico en telt daarom altijd als kritieke afwijking.','nee',
 'veiligheid','kritiek',
 'Er zijn geen losse of onveilige bouwdelen aangetroffen.',
 'Er is een los of potentieel gevaarlijk bouwdeel aangetroffen.',
 'Direct afzetten of borgen en dezelfde dag definitief vastzetten of verwijderen.',50),

-- SCHILDERWERK HOUT -----------------------------------------------------------
('SCH-02','SCH','Houten ondergrond','Houtrot',
 'Is actieve of onbehandelde houtrot zichtbaar of voelbaar?',
 'Prik bij twijfel met een priem; zacht hout onder een gesloten verflaag telt ook.','nee',
 'technisch','technisch',
 'Er is geen actieve of onbehandelde houtrot aanwezig.',
 'Er is actieve of onbehandelde houtrot geconstateerd in het behandelde vlak.',
 'Aangetast hout verwijderen tot op gezond hout en herstellen voordat verder wordt afgewerkt.',20),

('SCH-03','SCH','Houtverbindingen','Open houtverbindingen',
 'Zijn open houtverbindingen aanwezig waardoor vocht kan binnendringen?',
 null,'nee','technisch','technisch',
 'Houtverbindingen zijn gesloten, zodat vocht niet kan binnendringen.',
 'Er zijn open houtverbindingen aangetroffen waardoor vocht het hout kan binnendringen.',
 'Verbinding sluiten met een daarvoor geschikt product en daarna afwerken.',30),

('SCH-04','SCH','Verflaag','Loszittende verf',
 'Is loszittende, bladderende of onvoldoende hechtende verf aanwezig in het gereed behandelvlak?',
 null,'nee','technisch','technisch',
 'De verflaag zit in het gehele behandelvlak vast.',
 'In het gereed behandelvlak is loszittende of bladderende verf aangetroffen.',
 'Losse verf verwijderen, ondergrond voorbehandelen en het vlak opnieuw opbouwen.',40),

('SCH-06','SCH','Verflaag','Dekking',
 'Zijn kale plekken, doorschijnende grondlaag of onvoldoende gedekte reparaties zichtbaar?',
 'Beoordeel op ooghoogte bij daglicht, ook op de kopse en onderzijden.','nee',
 'esthetisch','technisch',
 'Het behandelvlak is volledig dekkend afgewerkt.',
 'Het schilderwerk is plaatselijk onvoldoende dekkend; kale plekken of doorschijnende ondergrond zijn zichtbaar.',
 'Vlak bijwerken tot volledige dekking, zo nodig over het gehele deelvlak.',60),

('SCH-07','SCH','Aflaklaag','Zakkers en druipers',
 'Zijn storend zichtbare zakkers of druipers aanwezig?',
 null,'nee','esthetisch','esthetisch',
 'De aflaklaag is vrij van storende zakkers en druipers.',
 'Plaatselijk zijn zakkers of druipers zichtbaar in de aflaklaag. De esthetische eindafwerking voldoet op deze locatie niet aan het afgesproken kwaliteitsniveau.',
 'Zakkers wegschuren en het vlak opnieuw aflakken.',70),

('SCH-08','SCH','Aflaklaag','Schuurkrassen',
 'Zijn grove schuurkrassen zichtbaar door de eindlaag?',
 null,'nee','esthetisch','esthetisch',
 'Er zijn geen grove schuurkrassen zichtbaar door de eindlaag.',
 'Door de eindlaag zijn grove schuurkrassen zichtbaar.',
 'Vlak fijner schuren, stofvrij maken en opnieuw aflakken.',80),

('SCH-09','SCH','Aflaklaag','Vuilinsluitingen',
 'Zijn storend zichtbare vuil- of stofinsluitingen aanwezig?',
 null,'nee','esthetisch','esthetisch',
 'De aflaklaag is vrij van storende vuil- en stofinsluitingen.',
 'In de aflaklaag zijn storende vuil- of stofinsluitingen aanwezig.',
 'Vlak schuren, stofvrij maken en opnieuw aflakken onder schonere omstandigheden.',90),

('SCH-12','SCH','Kopse kanten','Kopse houtvlakken',
 'Zijn onbehandelde blootliggende kopse houtvlakken aanwezig?',
 'Kopshout zuigt vocht op en is de meest voorkomende oorzaak van vervolgschade.','nee',
 'technisch','technisch',
 'Alle blootliggende kopse houtvlakken zijn behandeld.',
 'Er zijn onbehandelde blootliggende kopse houtvlakken aangetroffen.',
 'Kopse vlakken alsnog voorstrijken en in het systeem meenemen.',120),

('SCH-13','SCH','Omgeving','Verfspatten',
 'Zijn werkgerelateerde verfspatten aanwezig op aangrenzende materialen?',
 'Glas, metselwerk, bestrating, hemelwaterafvoer en beplanting.','nee',
 'esthetisch','esthetisch',
 'Aangrenzende materialen zijn vrij van verfspatten.',
 'Op aangrenzende materialen zijn werkgerelateerde verfspatten aangetroffen.',
 'Spatten verwijderen zonder de ondergrond te beschadigen.',130),

-- HOUTROTHERSTEL --------------------------------------------------------------
('HHR-01','HHR','Reparatie','Reparatie gesloten en vast',
 'Zijn zichtbare houtreparaties volledig gesloten, vast en vrij van scheuren of open randen?',
 null,'ja','technisch','technisch',
 'Houtreparaties zijn volledig gesloten, vast en vrij van scheuren.',
 'Een of meer houtreparaties zijn niet volledig gesloten of vertonen scheuren of open randen.',
 'Reparatie openen, opnieuw opbouwen volgens systeem en afwerken.',10),

('HHR-03','HHR','Ondergrond','Resthout',
 'Is bij een nog openliggende reparatie zacht of aangetast resthout zichtbaar?',
 'Alleen te beoordelen zolang de reparatie nog niet gesloten is.','nee',
 'technisch','technisch',
 'Er is geen zacht of aangetast resthout achtergebleven.',
 'In een openliggende reparatie is zacht of aangetast resthout achtergebleven.',
 'Uitfrezen tot op gezond hout en pas daarna de reparatie opbouwen.',30),

('HHR-04','HHR','Reparatie','Onthechting reparatie',
 'Zijn losstaande randen, onthechting of holtes zichtbaar aan de reparatie?',
 'Klop de reparatie af; hol geluid duidt op een holte achter het reparatiemateriaal.','nee',
 'technisch','technisch',
 'De reparatie hecht over het gehele vlak en is vrij van holtes.',
 'De reparatie vertoont losstaande randen, onthechting of holtes.',
 'Losse delen verwijderen en de reparatie opnieuw uitvoeren volgens het systeem.',40),

('HHR-05','HHR','Vorm','Profilering en waterafvoer',
 'Is de oorspronkelijke profilering en waterafvoerende vorm correct hersteld?',
 'Een vlak gemaakte waterhol of afgeronde neus laat water staan en geeft binnen enkele jaren opnieuw rot.','ja',
 'technisch','technisch',
 'Profilering en waterafvoerende vorm zijn conform het oorspronkelijke profiel hersteld.',
 'De oorspronkelijke profilering of de waterafvoerende vorm is niet correct hersteld.',
 'Profiel bijwerken zodat water wordt afgevoerd zoals in de oorspronkelijke situatie.',50),

('HHR-07','HHR','Eindafwerking','Zichtbaarheid reparatie',
 'Is de houtreparatie na eindafwerking onnodig zichtbaar door onvoldoende vlakheid of voorbereiding?',
 null,'nee','esthetisch','esthetisch',
 'De reparatie valt na eindafwerking niet onnodig op.',
 'De houtreparatie is na eindafwerking onnodig zichtbaar door onvoldoende vlakheid of voorbereiding.',
 'Vlak bijwerken, schuren en opnieuw afwerken.',70),

-- KOZIJNEN, RAMEN EN DEUREN ---------------------------------------------------
('KOZ-02','KOZ','Draaiend deel','Aanlopen',
 'Loopt het bewegende deel tijdens normale bediening tegen kozijn of dorpel?',
 null,'nee','functioneel','technisch',
 'Het bewegende deel loopt vrij van kozijn en dorpel.',
 'Het bewegende deel loopt tijdens normale bediening aan tegen kozijn of dorpel.',
 'Deel afstellen of bijwerken zodat het vrij loopt, zonder de sluitnaad te verliezen.',20),

('KOZ-05','KOZ','Hang- en sluitwerk','Hang- en sluitwerk',
 'Is het hang- en sluitwerk compleet, vast, functioneel en vrij van ernstige corrosie?',
 'Controleer op ontbrekende bevestiging, speling en aangetaste delen.','ja',
 'functioneel','technisch',
 'Hang- en sluitwerk is compleet, vast en functioneel.',
 'Het hang- en sluitwerk is niet compleet, zit los of functioneert niet naar behoren.',
 'Ontbrekende of aangetaste delen vervangen en alle bevestigingen vastzetten.',50),

('KOZ-06','KOZ','Afdichting','Rubbers en tochtprofielen',
 'Zijn de rubbers en tochtprofielen aanwezig, intact, vast, doorgaand en niet dichtgeschilderd?',
 'Overgeschilderde rubbers verliezen hun veerkracht en daarmee de afdichting.','ja',
 'functioneel','technisch',
 'Rubbers en tochtprofielen zijn aanwezig, doorgaand en functioneel.',
 'Rubbers of tochtprofielen ontbreken, zijn onderbroken, zitten los of zijn zodanig overgeschilderd dat het functioneren wordt belemmerd.',
 'Profiel herstellen of vervangen en bij schilderwerk afplakken.',60),

-- BEGLAZING -------------------------------------------------------------------
('GL-01','GL','Glas','Glasbreuk',
 'Is glasbreuk of een barst aanwezig?',
 null,'nee','veiligheid','kritiek',
 'Er is geen glasbreuk of barst aanwezig.',
 'Er is glasbreuk of een barst in de beglazing geconstateerd.',
 'Ruit direct veiligstellen en op korte termijn vervangen.',10),

('GL-02','GL','Isolatieglas','Condens in de spouw',
 'Is zichtbare condens of vervuiling in de isolatieglasspouw aanwezig die duidt op een defect?',
 null,'nee','technisch','technisch',
 'De isolatieglasspouw is helder; er is geen aanwijzing voor een defecte randafdichting.',
 'In de isolatieglasspouw is condens of vervuiling zichtbaar, wat duidt op een defecte randafdichting.',
 'Ruit opnemen in de vervangingslijst en de opdrachtgever informeren.',20),

('GL-03','GL','Glas','Nieuwe glasbeschadiging',
 'Is nieuwe glasbeschadiging veroorzaakt door de werkzaamheden aanwezig?',
 'Krassen door schrapen, inbranding door slijpvonken, etsplekken door reinigingsmiddel.','nee',
 'technisch','technisch',
 'Er is geen nieuwe glasbeschadiging door de werkzaamheden.',
 'Er is nieuwe glasbeschadiging aangetroffen die door de werkzaamheden is veroorzaakt.',
 'Ruit vervangen en de werkwijze aanpassen om herhaling te voorkomen.',30),

('GL-07','GL','Glaslat','Glaslat',
 'Zit de glaslat vast, is hij onbeschadigd, correct aangesloten en zijn de kopse kanten behandeld?',
 null,'ja','technisch','technisch',
 'Glaslatten zitten vast, zijn heel en correct aangesloten.',
 'Een of meer glaslatten zitten los, zijn gescheurd, sluiten niet correct aan of hebben onbehandelde kopse kanten.',
 'Glaslat vervangen of opnieuw bevestigen en volledig afwerken.',70),

('GL-09','GL','Sponning','Ontwatering en ventilatie',
 'Zijn de ontwaterings- en ventilatieopeningen vrij?',
 'Dichtgeschilderde of dichtgekitte openingen laten water in de sponning staan.','ja',
 'technisch','technisch',
 'Ontwaterings- en ventilatieopeningen zijn open en functioneel.',
 'Ontwaterings- of ventilatieopeningen zijn afgesloten of verstopt.',
 'Openingen vrijmaken en bij afwerking afschermen.',90),

('GL-10','GL','Veiligheidsglas','Veiligheidsglas aantoonbaar',
 'Is op de posities waar veiligheidsglas is vereist het type of de markering aantoonbaar?',
 'Is het type onbekend, kies dan NADER ONDERZOEK; niet gokken.','ja',
 'veiligheid','kritiek',
 'Op de posities waar veiligheidsglas is vereist, is het type aantoonbaar.',
 'Op een positie waar veiligheidsglas is vereist, is het glastype niet aantoonbaar.',
 'Glastype laten vaststellen door een specialist en zo nodig vervangen.',100),

-- KITWERK GEVEL ---------------------------------------------------------------
('KIT-01','KIT','Voeg','Voeg volledig gesloten',
 'Is de kitvoeg over de volle lengte gesloten, zonder gaten of open hoeken?',
 'Hoeken en aansluitingen zijn de plekken waar een voeg het eerst opengaat.','ja',
 'technisch','technisch',
 'De kitvoeg is over de volle lengte gesloten.',
 'De kitvoeg is niet over de volle lengte gesloten; er zijn gaten of open hoeken aanwezig.',
 'Voeg plaatselijk uitsnijden, reinigen en opnieuw afdichten.',10),

('KIT-02','KIT','Voeg','Onthechting voegflanken',
 'Is zichtbare onthechting aan de voegflanken aanwezig?',
 null,'nee','technisch','technisch',
 'De kit hecht aan beide voegflanken.',
 'Aan een of beide voegflanken is onthechting zichtbaar.',
 'Voeg verwijderen, flanken voorbehandelen volgens productblad en opnieuw afdichten.',20),

('KIT-05','KIT','Opbouw','Rugvulling',
 'Is rugvulling aanwezig waar die volgens de systeemopbouw vereist is?',
 'Alleen te beoordelen zolang de voeg nog open is.','ja',
 'technisch','technisch',
 'Rugvulling is aangebracht waar de systeemopbouw dat vereist.',
 'Op een plek waar rugvulling vereist is, ontbreekt deze.',
 'Voeg openen, rugvulling aanbrengen en opnieuw afdichten.',50),

('KIT-06','KIT','Opbouw','Driezijdige hechting',
 'Is bij een bewegingsvoeg sprake van ongewenste driezijdige hechting?',
 'Hecht de kit ook aan de bodem, dan scheurt de voeg bij de eerste beweging.','nee',
 'technisch','technisch',
 'Bewegingsvoegen hechten uitsluitend aan de twee flanken.',
 'Bij een bewegingsvoeg is sprake van driezijdige hechting.',
 'Voeg verwijderen, rugvulling of ontkleeflint aanbrengen en opnieuw afdichten.',60),

('KIT-08','KIT','Eindafwerking','Eindafwerking kitwerk',
 'Is de eindafwerking vrij van gaten, rafels, kitresten en losstaande randen?',
 null,'ja','esthetisch','esthetisch',
 'Het kitwerk is strak en schoon afgewerkt.',
 'Het kitwerk vertoont gaten, rafels, kitresten of losstaande randen.',
 'Voeg bijwerken en aangrenzende vlakken reinigen.',80),

-- METSELWERK ------------------------------------------------------------------
('MW-01','MW','Metselwerk','Losse gevelstenen',
 'Zijn losse gevelstenen aanwezig?',
 'Er wordt geen enkele losse steen geaccepteerd; een vallende steen is een veiligheidsrisico.','nee',
 'veiligheid','kritiek',
 'Er zijn geen losse gevelstenen aanwezig.',
 'Er zijn losse gevelstenen aangetroffen.',
 'Gebied direct afzetten en de steen opnieuw vastzetten of vervangen.',10),

('MW-04','MW','Metselwerk','Nieuwe steenbeschadiging',
 'Zijn nieuwe beschadigde stenen door de werkzaamheden aanwezig?',
 null,'nee','technisch','technisch',
 'Er zijn geen nieuwe steenbeschadigingen door de werkzaamheden.',
 'Er zijn nieuw beschadigde stenen aangetroffen die door de werkzaamheden zijn ontstaan.',
 'Beschadigde stenen vervangen en de werkwijze aanpassen.',40),

('MW-05','MW','Herstel','Vervangende stenen',
 'Komen de vervangende stenen overeen met het bestaande werk in formaat, kleur, textuur en structuur?',
 'Vergelijk zo mogelijk met het goedgekeurde referentievlak.','ja',
 'esthetisch','esthetisch',
 'Vervangende stenen sluiten aan bij het bestaande metselwerk.',
 'De vervangende stenen wijken zichtbaar af van het bestaande metselwerk in formaat, kleur, textuur of structuur.',
 'Steenkeuze heroverwegen en het herstelvlak opnieuw uitvoeren.',50),

('MW-06','MW','Herstel','Metselverband',
 'Zet het herstel het bestaande metselverband correct voort?',
 null,'ja','esthetisch','esthetisch',
 'Het herstel zet het bestaande metselverband voort.',
 'Het herstelvlak onderbreekt het bestaande metselverband.',
 'Herstelvlak uithakken en opnieuw metselen in het juiste verband.',60),

('MW-08','MW','Netheid','Mortel- en cementvervuiling',
 'Is ernstige nieuwe mortel- of cementvervuiling aanwezig?',
 null,'nee','esthetisch','esthetisch',
 'Het metselwerk is vrij van nieuwe mortel- en cementvervuiling.',
 'Op het metselwerk is nieuwe mortel- of cementvervuiling aangetroffen.',
 'Vervuiling verwijderen met een voor deze steen geschikte methode.',80),

-- VOEGWERK --------------------------------------------------------------------
('VW-01','VW','Voegwerk','Los nieuw voegwerk',
 'Is nieuw voegwerk aanwezig dat loszit?',
 null,'nee','technisch','technisch',
 'Het nieuwe voegwerk zit vast.',
 'Er is nieuw voegwerk aangetroffen dat loszit.',
 'Los voegwerk uithakken en opnieuw voegen.',10),

('VW-02','VW','Voegwerk','Vulling',
 'Zijn de voegen volledig gevuld volgens het voorgeschreven profiel?',
 null,'ja','technisch','technisch',
 'De voegen zijn volledig gevuld volgens het voorgeschreven profiel.',
 'Voegen zijn niet volledig gevuld volgens het voorgeschreven profiel.',
 'Voegen navullen en afwerken in het juiste profiel.',20),

('VW-03','VW','Voegwerk','Scheuren en uitvallende mortel',
 'Zijn losstaande voegen, scheuren langs de steen of uitvallende mortel aanwezig?',
 null,'nee','technisch','technisch',
 'Het voegwerk is vrij van scheuren en uitvallende mortel.',
 'Er zijn losstaande voegen, scheuren langs de steen of uitvallende mortel aangetroffen.',
 'Aangetast voegwerk uithakken en opnieuw voegen.',30),

('VW-06','VW','Kleur','Voegkleur',
 'Komt de voegkleur overeen met het goedgekeurde referentievlak of proefvlak?',
 'Beoordeel bij droge voeg en diffuus daglicht; natte voeg is altijd donkerder.','ja',
 'esthetisch','esthetisch',
 'De voegkleur komt overeen met het goedgekeurde referentievlak.',
 'De voegkleur wijkt zichtbaar af van het goedgekeurde referentievlak.',
 'Mengverhouding controleren en het afwijkende vlak opnieuw voegen.',60),

('VW-07','VW','Uitvoering','Regelmaat voegwerk',
 'Is sterk afwijkende voegbreedte, voegdiepte of een afwijkend voegprofiel aanwezig?',
 null,'nee','esthetisch','esthetisch',
 'Voegbreedte, -diepte en -profiel zijn regelmatig uitgevoerd.',
 'Er is sterk afwijkende voegbreedte, voegdiepte of een afwijkend voegprofiel aangetroffen.',
 'Afwijkend vlak uithakken en opnieuw voegen.',70),

('VW-08','VW','Steen','Hak- en slijpschade',
 'Is nieuwe hak- of slijpschade aan de steen buiten het herstelgebied aanwezig?',
 null,'nee','technisch','technisch',
 'Buiten het herstelgebied is geen hak- of slijpschade ontstaan.',
 'Buiten het herstelgebied is nieuwe hak- of slijpschade aan de steen aangetroffen.',
 'Beschadigde stenen vervangen en de uitvoeringsmethode aanpassen.',80),

-- GEVELREINIGING --------------------------------------------------------------
('GR-01','GR','Voorbereiding','Proefvlak',
 'Is een goedgekeurd proefvlak aanwezig waar dat is vereist?',
 null,'ja','technisch','technisch',
 'Er is een goedgekeurd proefvlak aanwezig.',
 'Er is gereinigd zonder goedgekeurd proefvlak, terwijl dat wel was vereist.',
 'Reiniging stilleggen, proefvlak maken en laten goedkeuren.',10),

('GR-02','GR','Resultaat','Gereinigd beeld',
 'Is het gereinigde beeld vergelijkbaar met het goedgekeurde referentievlak?',
 null,'ja','esthetisch','esthetisch',
 'Het gereinigde beeld is vergelijkbaar met het referentievlak.',
 'Het gereinigde beeld wijkt af van het goedgekeurde referentievlak.',
 'Reinigingsmethode bijstellen en het vlak nabehandelen.',20),

('GR-03','GR','Steen','Beschadiging steen',
 'Is beschadiging van de steen door het reinigen zichtbaar?',
 'Let op opgeruwde bakhuid, uitgespoelde voegen en drukstralen-sporen.','nee',
 'technisch','technisch',
 'De steen is niet beschadigd door de reiniging.',
 'De steen is door de reiniging beschadigd.',
 'Reiniging direct staken, druk of middel bijstellen en herstel bepalen.',30),

('GR-04','GR','Voegwerk','Voegschade door reiniging',
 'Is schade aan het voegwerk door het reinigen zichtbaar?',
 null,'nee','technisch','technisch',
 'Het voegwerk is niet beschadigd door de reiniging.',
 'Het voegwerk is door de reiniging aangetast.',
 'Reiniging bijstellen en aangetast voegwerk herstellen.',40),

('GR-05','GR','Nabehandeling','Reinigingsmiddelresidu',
 'Is residu van het reinigingsmiddel op de gevel achtergebleven?',
 'Achtergebleven middel geeft na weken uitbloei of verkleuring.','nee',
 'technisch','technisch',
 'Er is geen residu van het reinigingsmiddel achtergebleven.',
 'Op de gevel is residu van het reinigingsmiddel achtergebleven.',
 'Gevel volgens productvoorschrift naspoelen of neutraliseren.',50),

('GR-06','GR','Resultaat','Banen en vlekken',
 'Zijn storende banen of vlekken in het gereinigde vlak zichtbaar?',
 null,'nee','esthetisch','esthetisch',
 'Het gereinigde vlak is gelijkmatig van beeld.',
 'In het gereinigde vlak zijn storende banen of vlekken zichtbaar.',
 'Vlak gelijkmatig nabehandelen.',60),

-- GEVELCOATING ----------------------------------------------------------------
('GC-01','GC','Ondergrond','Draagkrachtige ondergrond',
 'Is de ondergrond draagkrachtig, schoon en geschikt om te coaten?',
 null,'ja','technisch','technisch',
 'De ondergrond is draagkrachtig en schoon.',
 'De ondergrond is niet draagkrachtig of niet schoon genoeg om te coaten.',
 'Ondergrond alsnog voorbehandelen volgens het systeemvoorschrift voordat wordt gecoat.',10),

('GC-07','GC','Systeem','Systeemopbouw',
 'Is de systeemopbouw uitgevoerd zoals voorgeschreven (voorstrijk, tussenlaag, aflaag)?',
 null,'ja','technisch','technisch',
 'De systeemopbouw is uitgevoerd zoals voorgeschreven.',
 'De uitgevoerde systeemopbouw wijkt af van het voorschrift.',
 'Ontbrekende lagen alsnog aanbrengen of het vlak opnieuw opbouwen.',70),

('GC-08','GC','Resultaat','Volledige dekking',
 'Is het vlak volledig dekkend gecoat?',
 null,'ja','esthetisch','technisch',
 'Het vlak is volledig dekkend gecoat.',
 'Het vlak is niet volledig dekkend gecoat.',
 'Extra laag aanbrengen over het gehele deelvlak.',80),

('GC-09','GC','Resultaat','Blazen',
 'Zijn blazen in de coating zichtbaar?',
 'Blazen wijzen bijna altijd op vocht of onvoldoende droging tussen de lagen.','nee',
 'technisch','technisch',
 'De coating is vrij van blazen.',
 'In de coating zijn blazen zichtbaar.',
 'Oorzaak vaststellen, aangetaste laag verwijderen en het vlak opnieuw opbouwen.',90),

('GC-10','GC','Resultaat','Onthechting coating',
 'Is onthechting van de coating zichtbaar?',
 null,'nee','technisch','technisch',
 'De coating hecht over het gehele vlak.',
 'De coating vertoont onthechting.',
 'Losse coating verwijderen, ondergrond voorbehandelen en opnieuw coaten.',100),

('GC-11','GC','Resultaat','Uniform kleurbeeld',
 'Is het kleurbeeld over het gehele vlak uniform?',
 null,'ja','esthetisch','esthetisch',
 'Het kleurbeeld is uniform.',
 'Het kleurbeeld van de coating is niet uniform.',
 'Vlak in een keer doorwerken en zo nodig opnieuw aflagen.',110),

('GC-12','GC','Resultaat','Banen en aanzetten',
 'Zijn storende banen of aanzetten zichtbaar?',
 'Aanzetten ontstaan bij het onderbreken van een vlak; werk nat-in-nat door tot een natuurlijke stopplaats.','nee',
 'esthetisch','esthetisch',
 'Het vlak is vrij van storende banen en aanzetten.',
 'In het gecoate vlak zijn storende banen of aanzetten zichtbaar.',
 'Deelvlak opnieuw aflagen tot een natuurlijke stopplaats.',120),

-- BETONHERSTEL ----------------------------------------------------------------
('BET-01','BET','Beton','Los beton',
 'Is los of hol klinkend beton aanwezig?',
 'Klop het vlak af; hol geluid duidt op onthechting of achterliggende wapeningscorrosie.','nee',
 'veiligheid','kritiek',
 'Er is geen los of hol klinkend beton aanwezig.',
 'Er is los of hol klinkend beton aangetroffen.',
 'Gebied direct afzetten, los beton verwijderen en herstellen volgens systeem.',10),

('BET-03','BET','Wapening','Roestende wapening',
 'Is roestende wapening zichtbaar in gereed herstelwerk?',
 null,'nee','technisch','kritiek',
 'In het gereed herstelwerk is geen roestende wapening zichtbaar.',
 'In gereed herstelwerk is roestende wapening zichtbaar.',
 'Herstel openen, wapening ontroesten en passiveren, daarna opnieuw opbouwen.',30),

('BET-04','BET','Reparatie','Losse randen reparatie',
 'Zijn losse randen aan de betonreparatie zichtbaar?',
 null,'nee','technisch','technisch',
 'De betonreparatie heeft geen losse randen.',
 'De betonreparatie vertoont losse randen.',
 'Randen uithakken tot vaste ondergrond en opnieuw aanhelen.',40),

('BET-05','BET','Reparatie','Holklinkende reparatie',
 'Klinkt de reparatie hol?',
 null,'nee','technisch','technisch',
 'De reparatie klinkt overal vast.',
 'De betonreparatie klinkt hol, wat duidt op onvoldoende hechting.',
 'Reparatie verwijderen en opnieuw uitvoeren volgens systeemvoorschrift.',50),

('BET-07','BET','Vorm','Vorm en profilering',
 'Is de oorspronkelijke vorm en profilering correct hersteld?',
 null,'ja','esthetisch','technisch',
 'Vorm en profilering zijn correct hersteld.',
 'De vorm of profilering van het betonelement is niet correct hersteld.',
 'Profiel bijwerken volgens de oorspronkelijke maatvoering.',70),

('BET-09','BET','Esthetiek','Aansluiting herstelvlak',
 'Sluit het herstelvlak esthetisch aan op het bestaande beton?',
 null,'ja','esthetisch','esthetisch',
 'Het herstelvlak sluit esthetisch aan op het bestaande beton.',
 'Het herstelvlak wijkt zichtbaar af van het bestaande beton.',
 'Vlak nabehandelen of coaten volgens afspraak met de opdrachtgever.',90),

-- STUC- EN PLEISTERWERK -------------------------------------------------------
('STU-01','STU','Stucwerk','Losse en holklinkende delen',
 'Zijn losse of holklinkende delen aanwezig?',
 null,'nee','technisch','kritiek',
 'Het stucwerk zit over het gehele vlak vast.',
 'Er zijn losse of holklinkende delen in het stucwerk aangetroffen.',
 'Losse delen verwijderen tot vaste ondergrond en opnieuw opbouwen.',10),

('STU-02','STU','Stucwerk','Nieuwe scheuren',
 'Zijn nieuwe zichtbare scheuren aanwezig?',
 null,'nee','technisch','technisch',
 'Er zijn geen nieuwe scheuren in het stucwerk.',
 'In het stucwerk zijn nieuwe scheuren zichtbaar.',
 'Scheur openen, wapenen en het vlak opnieuw afwerken.',20),

('STU-04','STU','Herstel','Reparatieovergang',
 'Is de overgang tussen herstel en bestaand stucwerk vlak en onopvallend?',
 null,'ja','esthetisch','esthetisch',
 'De reparatieovergang is vlak en onopvallend.',
 'De overgang tussen herstel en bestaand stucwerk is zichtbaar.',
 'Overgang uitvlakken en het deelvlak in een keer afwerken.',40),

('STU-05','STU','Structuur','Structuur',
 'Komt de structuur overeen met het bestaande werk of het referentievlak?',
 null,'ja','esthetisch','esthetisch',
 'De structuur komt overeen met het referentievlak.',
 'De structuur van het herstelvlak wijkt af van het bestaande werk.',
 'Vlak opnieuw opzetten met de juiste korrel en techniek.',50),

('STU-06','STU','Kleur','Kleurbeeld stucwerk',
 'Is het kleurbeeld gelijkmatig en in overeenstemming met het referentievlak?',
 null,'ja','esthetisch','esthetisch',
 'Het kleurbeeld is gelijkmatig.',
 'Het kleurbeeld van het stucwerk is niet gelijkmatig of wijkt af van het referentievlak.',
 'Vlak in zijn geheel nabehandelen.',60),

-- HOUTEN GEVELBEKLEDING -------------------------------------------------------
('GBH-01','GBH','Delen','Delen vast',
 'Zitten alle delen vast?',
 null,'ja','veiligheid','kritiek',
 'Alle delen van de gevelbekleding zitten vast.',
 'Een of meer delen van de houten gevelbekleding zitten los.',
 'Delen direct opnieuw bevestigen volgens het systeem.',10),

('GBH-02','GBH','Delen','Breuk en scheuren',
 'Zijn gebroken, gescheurde of kromgetrokken delen aanwezig?',
 null,'nee','technisch','technisch',
 'De delen zijn heel en vlak.',
 'Er zijn gebroken, gescheurde of kromgetrokken delen aangetroffen.',
 'Aangetaste delen vervangen.',20),

('GBH-03','GBH','Naden','Naden conform systeem',
 'Zijn de naden uitgevoerd conform het systeem?',
 null,'ja','technisch','technisch',
 'De naden zijn uitgevoerd conform het systeem.',
 'De naadafwerking wijkt af van het systeem.',
 'Naden herstellen volgens het detailblad.',30),

('GBH-04','GBH','Uitlijning','Uitlijning',
 'Zijn de delen recht en gelijkmatig uitgelijnd?',
 null,'ja','esthetisch','esthetisch',
 'De delen zijn recht en gelijkmatig uitgelijnd.',
 'De gevelbekleding is niet recht of ongelijkmatig uitgelijnd.',
 'Delen opnieuw stellen.',40),

('GBH-05','GBH','Bevestiging','Bevestigingsmiddelen',
 'Zijn de bevestigingsmiddelen compleet en corrosievast?',
 null,'ja','technisch','technisch',
 'De bevestigingsmiddelen zijn compleet en corrosievast.',
 'Er ontbreken bevestigingsmiddelen of er is corrosie aan bevestigingsmiddelen zichtbaar.',
 'Ontbrekende bevestiging aanbrengen en corroderende middelen vervangen.',50),

('GBH-06','GBH','Ventilatie','Ventilatieopeningen vrij',
 'Zijn de ventilatieopeningen achter de bekleding vrij?',
 'Een dichtgezette spouw laat de bekleding aan de achterzijde rotten.','ja',
 'technisch','technisch',
 'De ventilatieopeningen zijn vrij.',
 'Ventilatieopeningen achter de gevelbekleding zijn afgesloten of verstopt.',
 'Openingen vrijmaken en zo nodig ventilatieprofiel aanbrengen.',60),

('GBH-07','GBH','Hout','Houtrot en kopse kanten',
 'Is houtrot of een onbehandelde kopse kant aanwezig?',
 null,'nee','technisch','technisch',
 'De bekleding is vrij van houtrot en alle kopse kanten zijn behandeld.',
 'Er is houtrot of een onbehandelde kopse kant aan de gevelbekleding aangetroffen.',
 'Aangetast deel vervangen en alle kopse kanten alsnog behandelen.',70),

-- PLAAT- EN METALEN GEVELBEKLEDING --------------------------------------------
('GBM-01','GBM','Platen','Platen vast',
 'Zitten alle platen vast?',
 null,'ja','veiligheid','kritiek',
 'Alle platen zitten vast.',
 'Een of meer platen van de gevelbekleding zitten los.',
 'Platen direct opnieuw bevestigen volgens het systeem.',10),

('GBM-02','GBM','Platen','Breuk, deuk en delaminatie',
 'Zijn breuk, deuken, scheuren of delaminatie aanwezig?',
 null,'nee','technisch','technisch',
 'De platen zijn onbeschadigd.',
 'Er zijn platen met breuk, deuken, scheuren of delaminatie aangetroffen.',
 'Beschadigde platen vervangen.',20),

('GBM-03','GBM','Naden','Naden conform systeem',
 'Zijn de naden en voegen uitgevoerd conform het systeem?',
 null,'ja','technisch','technisch',
 'De naden zijn uitgevoerd conform het systeem.',
 'De naadafwerking wijkt af van het systeem.',
 'Naden herstellen volgens het detailblad.',30),

('GBM-04','GBM','Uitlijning','Uitlijning',
 'Zijn de platen recht en gelijkmatig uitgelijnd?',
 null,'ja','esthetisch','esthetisch',
 'De platen zijn recht en gelijkmatig uitgelijnd.',
 'De platen zijn niet recht of ongelijkmatig uitgelijnd.',
 'Platen opnieuw stellen.',40),

('GBM-05','GBM','Bevestiging','Bevestigingsmiddelen',
 'Zijn de bevestigingsmiddelen compleet en corrosievast?',
 null,'ja','technisch','technisch',
 'De bevestigingsmiddelen zijn compleet en corrosievast.',
 'Er ontbreken bevestigingsmiddelen of er is corrosie zichtbaar.',
 'Ontbrekende bevestiging aanbrengen en corroderende middelen vervangen.',50),

('GBM-06','GBM','Ventilatie','Ventilatieopeningen vrij',
 'Zijn de ventilatieopeningen achter de bekleding vrij?',
 null,'ja','technisch','technisch',
 'De ventilatieopeningen zijn vrij.',
 'Ventilatieopeningen achter de gevelbekleding zijn afgesloten of verstopt.',
 'Openingen vrijmaken.',60),

-- METAALCONSERVERING ----------------------------------------------------------
('MET-01','MET','Staal','Actieve roest',
 'Is actieve roest zichtbaar?',
 null,'nee','technisch','technisch',
 'Er is geen actieve roest zichtbaar.',
 'Er is actieve roest aangetroffen.',
 'Roest verwijderen tot de voorgeschreven reinheidsgraad en het systeem opnieuw opbouwen.',10),

('MET-02','MET','Coating','Losse coating',
 'Is losse coating aanwezig?',
 null,'nee','technisch','technisch',
 'De coating zit over het gehele vlak vast.',
 'Er is losse coating aangetroffen.',
 'Losse coating verwijderen, ondergrond voorbehandelen en opnieuw opbouwen.',20),

('MET-03','MET','Coating','Volledige dekking',
 'Is het vlak volledig dekkend geconserveerd, inclusief randen, lassen en achterzijden?',
 'Randen en lasnaden zijn de plekken waar corrosie het eerst terugkomt.','ja',
 'technisch','technisch',
 'Het vlak is volledig dekkend geconserveerd.',
 'Het conserveringssysteem is niet overal volledig dekkend aangebracht.',
 'Ontbrekende delen alsnog opbouwen volgens systeem.',30),

('MET-05','MET','Beschadiging','Onbehandelde beschadiging',
 'Is onbehandelde beschadiging in de conservering aanwezig?',
 null,'nee','technisch','technisch',
 'Beschadigingen in de conservering zijn bijgewerkt.',
 'Er is onbehandelde beschadiging in de conservering aangetroffen.',
 'Beschadiging bijwerken volgens het herstelvoorschrift van het systeem.',50),

('MET-06','MET','Afwerking','Zakkers en druipers',
 'Zijn zakkers of druipers in de conservering zichtbaar?',
 null,'nee','esthetisch','esthetisch',
 'De conservering is vrij van zakkers en druipers.',
 'In de conservering zijn zakkers of druipers zichtbaar.',
 'Zakkers wegschuren en het vlak opnieuw aflagen.',60),

('MET-07','MET','Afwerking','Uniform kleurbeeld',
 'Is het kleurbeeld uniform?',
 null,'ja','esthetisch','esthetisch',
 'Het kleurbeeld is uniform.',
 'Het kleurbeeld van de conservering is niet uniform.',
 'Vlak opnieuw aflagen.',70),

-- DAKRANDEN EN BOEIDELEN ------------------------------------------------------
('DR-01','DR','Bevestiging','Bevestiging dakrand',
 'Is de dakrand of het boeideel over de volle lengte deugdelijk bevestigd?',
 null,'ja','veiligheid','kritiek',
 'De dakrand is over de volle lengte deugdelijk bevestigd.',
 'De dakrand of het boeideel is niet over de volle lengte deugdelijk bevestigd.',
 'Bevestiging direct herstellen volgens detail.',10),

('DR-02','DR','Hout','Houtrot boeideel',
 'Is houtrot in het boeideel aanwezig?',
 null,'nee','technisch','technisch',
 'Het boeideel is vrij van houtrot.',
 'In het boeideel is houtrot aangetroffen.',
 'Aangetast deel vervangen of herstellen en opnieuw afwerken.',20),

('DR-03','DR','Naden','Open naden',
 'Zijn open naden in de dakrandafwerking aanwezig?',
 null,'nee','technisch','technisch',
 'De dakrandafwerking is gesloten.',
 'In de dakrandafwerking zijn open naden aangetroffen.',
 'Naden sluiten volgens het toepasselijke detail.',30),

('DR-04','DR','Water','Waterafvoer dakrand',
 'Voert de dakrand het water af zoals bedoeld, zonder terugloop naar de gevel?',
 null,'ja','technisch','technisch',
 'De dakrand voert het water af zoals bedoeld.',
 'De dakrand voert het water niet af zoals bedoeld; er is terugloop naar de gevel.',
 'Afschot of waterhol herstellen.',40),

('DR-05','DR','Coating','Coating dakrand',
 'Is de coating of afwerking van de dakrand intact?',
 null,'ja','technisch','esthetisch',
 'De afwerking van de dakrand is intact.',
 'De coating of afwerking van de dakrand is niet intact.',
 'Afwerking bijwerken of vernieuwen.',50),

('DR-06','DR','Aansluiting','Aansluiting op dakbedekking',
 'Is de aansluiting op de dakbedekking correct en gesloten uitgevoerd?',
 null,'ja','technisch','kritiek',
 'De aansluiting op de dakbedekking is correct en gesloten.',
 'De aansluiting tussen dakrand en dakbedekking is niet correct of niet gesloten.',
 'Detail opnieuw uitvoeren volgens het systeemvoorschrift.',60),

-- PLAT DAK --------------------------------------------------------------------
('PD-01','PD','Dakbedekking','Open naden',
 'Zijn open naden in de dakbedekking aanwezig?',
 null,'nee','technisch','kritiek',
 'Alle naden in de dakbedekking zijn gesloten.',
 'Er zijn open naden in de dakbedekking aangetroffen.',
 'Naad direct sluiten volgens systeemvoorschrift; bij regen tijdelijk waterdicht maken.',10),

('PD-02','PD','Dakbedekking','Perforaties en sneden',
 'Zijn perforaties of sneden in de dakbedekking aanwezig?',
 null,'nee','technisch','kritiek',
 'De dakbedekking is vrij van perforaties en sneden.',
 'In de dakbedekking zijn perforaties of sneden aangetroffen.',
 'Beschadiging direct dichtzetten met een systeemconforme reparatie.',20),

('PD-03','PD','Dakbedekking','Nieuwe blazen',
 'Zijn nieuwe blazen in de dakbedekking zichtbaar?',
 null,'nee','technisch','technisch',
 'Er zijn geen nieuwe blazen in de dakbedekking.',
 'In de dakbedekking zijn nieuwe blazen zichtbaar.',
 'Blaas opensnijden, laten drogen en systeemconform dichtzetten.',30),

('PD-04','PD','Opstanden','Opstanden aangesloten',
 'Zijn alle opstanden volledig aangesloten en afgewerkt?',
 null,'ja','technisch','kritiek',
 'Alle opstanden zijn volledig aangesloten en afgewerkt.',
 'Een of meer opstanden zijn niet volledig aangesloten of afgewerkt.',
 'Opstand alsnog volledig aansluiten volgens detail.',40),

('PD-05','PD','Doorvoeren','Doorvoeren waterdicht',
 'Zijn alle doorvoeren waterdicht afgewerkt?',
 null,'ja','technisch','kritiek',
 'Alle doorvoeren zijn waterdicht afgewerkt.',
 'Een of meer doorvoeren zijn niet waterdicht afgewerkt.',
 'Doorvoer opnieuw afwerken met een systeemconforme manchet.',50),

('PD-06','PD','Bevestiging','Kimfixatie',
 'Is de kimfixatie aanwezig waar het systeem die vereist?',
 'Alleen beoordelen zolang het detail zichtbaar is.','ja',
 'technisch','technisch',
 'De kimfixatie is aanwezig waar het systeem die vereist.',
 'De kimfixatie ontbreekt op een plek waar het systeem die vereist.',
 'Kimfixatie alsnog aanbrengen volgens het systeemvoorschrift.',60),

('PD-07','PD','Documentatie','Documentatie windweerstand',
 'Is de systeem- of KOMO-documentatie voor de windweerstand aanwezig en van toepassing op dit dak?',
 'Documentcontrole conform NEN 6707 en NPR 6708; nooit zelf een waarde bepalen. Ontbreekt de documentatie, kies dan NADER ONDERZOEK.','ja',
 'technisch','technisch',
 'De windweerstandsdocumentatie is aanwezig en van toepassing op dit dak.',
 'De systeem- of KOMO-documentatie voor de windweerstand ontbreekt of is niet van toepassing op dit dak.',
 'Documentatie opvragen bij de leverancier en de bevestiging laten toetsen.',70),

('PD-08','PD','Afvoeren','Afvoeren vrij',
 'Zijn alle dakafvoeren en noodoverlopen vrij?',
 null,'ja','technisch','technisch',
 'Alle dakafvoeren en noodoverlopen zijn vrij.',
 'Een of meer dakafvoeren of noodoverlopen zijn verstopt.',
 'Afvoer vrijmaken en de bladvanger controleren.',80),

('PD-09','PD','Water','Abnormale plasvorming',
 'Is abnormale plasvorming op het dak aanwezig?',
 'Registreer omvang en plaats met foto; plasvorming duidt op onvoldoende afschot of een doorbuigende constructie.','nee',
 'technisch','observatie',
 'Er is geen abnormale plasvorming op het dak.',
 'Op het dak is abnormale plasvorming aangetroffen.',
 'Oorzaak vaststellen en afschot of afvoercapaciteit aanpassen.',90),

-- HELLEND DAK -----------------------------------------------------------------
('HD-01','HD','Pannen','Gebroken of verschoven pannen',
 'Zijn gebroken, ontbrekende of verschoven pannen aanwezig?',
 null,'nee','technisch','technisch',
 'De pannen zijn heel, compleet en liggen op hun plaats.',
 'Er zijn gebroken, ontbrekende of verschoven pannen aangetroffen.',
 'Pannen vervangen en opnieuw stellen.',10),

('HD-02','HD','Bevestiging','Bevestiging pannen',
 'Zijn de pannen bevestigd conform het systeem en de windbelastingzone?',
 null,'ja','veiligheid','kritiek',
 'De pannen zijn bevestigd conform het systeem.',
 'De pannenbevestiging wijkt af van het systeemvoorschrift.',
 'Bevestiging aanvullen volgens het bevestigingsplan.',20),

('HD-03','HD','Nok','Nok vast',
 'Zit de nokafwerking vast?',
 null,'ja','veiligheid','kritiek',
 'De nokafwerking zit vast.',
 'De nokafwerking zit los.',
 'Nokvorsten opnieuw bevestigen volgens systeem.',30),

('HD-04','HD','Kilgoot','Kilgoten vrij',
 'Zijn de kilgoten vrij en onbeschadigd?',
 null,'ja','technisch','technisch',
 'De kilgoten zijn vrij en onbeschadigd.',
 'Een of meer kilgoten zijn verstopt of beschadigd.',
 'Kilgoot vrijmaken en beschadiging herstellen.',40),

('HD-05','HD','Doorvoeren','Doorvoeren waterkerend',
 'Zijn de doorvoeren waterkerend uitgevoerd?',
 null,'ja','technisch','technisch',
 'De doorvoeren zijn waterkerend uitgevoerd.',
 'Een of meer doorvoeren zijn niet waterkerend uitgevoerd.',
 'Doorvoer opnieuw afwerken volgens detail.',50),

('HD-06','HD','Aansluiting','Lood- en zinkaansluitingen',
 'Zijn de lood- en zinkaansluitingen correct uitgevoerd?',
 null,'ja','technisch','technisch',
 'De lood- en zinkaansluitingen zijn correct uitgevoerd.',
 'Een of meer lood- of zinkaansluitingen zijn niet correct uitgevoerd.',
 'Aansluiting opnieuw uitvoeren volgens detail.',60),

-- LOOD- EN ZINKWERK -----------------------------------------------------------
('LZ-01','LZ','Materiaal','Scheuren en gaten',
 'Zijn open scheuren of gaten in het lood- of zinkwerk aanwezig?',
 null,'nee','technisch','kritiek',
 'Het lood- en zinkwerk is vrij van scheuren en gaten.',
 'In het lood- of zinkwerk zijn open scheuren of gaten aangetroffen.',
 'Deel vervangen; plaatselijk dichtsmeren is geen duurzame oplossing.',10),

('LZ-02','LZ','Verbindingen','Soldeernaden',
 'Zijn de soldeernaden gesloten?',
 null,'ja','technisch','technisch',
 'De soldeernaden zijn gesloten.',
 'Er zijn open soldeernaden aangetroffen.',
 'Naad opnieuw solderen.',20),

('LZ-03','LZ','Verbindingen','Overlap',
 'Is de overlap uitgevoerd conform het systeem en de dakhelling?',
 null,'ja','technisch','technisch',
 'De overlap is uitgevoerd conform het systeem.',
 'De overlap voldoet niet aan het systeemvoorschrift.',
 'Detail opnieuw uitvoeren met de voorgeschreven overlap.',30),

('LZ-04','LZ','Water','Afschot en waterafvoer',
 'Voert het lood- of zinkwerk het water af zonder stagnatie?',
 null,'ja','technisch','technisch',
 'Het water wordt afgevoerd zonder stagnatie.',
 'Er is stagnatie in de waterafvoer van het lood- of zinkwerk.',
 'Afschot herstellen.',40),

('LZ-05','LZ','Werking','Thermische werking',
 'Is er voldoende ruimte voor thermische werking (schuifnaden, stroken op lengte)?',
 'Te lange stroken zonder schuifnaad scheuren binnen enkele jaren.','ja',
 'technisch','technisch',
 'Er is voldoende ruimte voor thermische werking.',
 'Het lood- of zinkwerk heeft onvoldoende ruimte voor thermische werking.',
 'Stroken inkorten en schuifnaden aanbrengen volgens voorschrift.',50),

('LZ-06','LZ','Bevestiging','Bevestiging vast',
 'Zit het lood- of zinkwerk deugdelijk bevestigd?',
 null,'ja','veiligheid','kritiek',
 'Het lood- en zinkwerk zit deugdelijk bevestigd.',
 'Het lood- of zinkwerk zit onvoldoende bevestigd.',
 'Bevestiging direct herstellen.',60),

-- HEMELWATERAFVOER ------------------------------------------------------------
('HWA-01','HWA','Goot','Goten vrij',
 'Zijn de goten vrij van blad en vuil?',
 null,'ja','technisch','technisch',
 'De goten zijn vrij.',
 'De goten zijn niet vrij van blad en vuil.',
 'Goten reinigen.',10),

('HWA-02','HWA','Afvoer','Afvoer vrij',
 'Zijn de hemelwaterafvoeren vrij en werkend?',
 null,'ja','technisch','technisch',
 'De hemelwaterafvoeren zijn vrij en werkend.',
 'Een of meer hemelwaterafvoeren zijn verstopt.',
 'Afvoer doorspuiten en zo nodig een bladvanger plaatsen.',20),

('HWA-04','HWA','Bevestiging','Beugels aanwezig en vast',
 'Zijn alle beugels aanwezig en vast?',
 null,'ja','technisch','technisch',
 'Alle beugels zijn aanwezig en vast.',
 'Er ontbreken beugels of beugels zitten los.',
 'Beugels aanvullen en vastzetten.',40),

('HWA-05','HWA','Verbindingen','Verbindingen lekvrij',
 'Zijn de verbindingen lekvrij?',
 null,'ja','technisch','technisch',
 'De verbindingen zijn lekvrij.',
 'Er zijn lekkende verbindingen in de hemelwaterafvoer aangetroffen.',
 'Verbinding herstellen of vervangen.',50),

-- BALUSTRADES EN HEKWERKEN ----------------------------------------------------
('BAL-01','BAL','Constructie','Stabiliteit balustrade',
 'Is de balustrade of het hekwerk stabiel bij normale belasting?',
 'Duw met beide handen op leuninghoogte. Beweging betekent altijd een kritieke afwijking: dit is een valbeveiliging.','ja',
 'veiligheid','kritiek',
 'De balustrade is stabiel bij normale belasting.',
 'De balustrade of het hekwerk is niet stabiel bij normale belasting. Dit betreft een valbeveiliging en is daarmee een kritieke afwijking.',
 'Gebied direct afzetten of tijdelijk afschermen en dezelfde dag herstellen.',10),

('BAL-02','BAL','Bevestiging','Bevestiging balustrade',
 'Is de bevestiging compleet en vast?',
 null,'ja','veiligheid','kritiek',
 'De bevestiging is compleet en vast.',
 'De bevestiging van de balustrade is niet compleet of zit los.',
 'Bevestiging direct herstellen volgens detail.',20),

('BAL-03','BAL','Staal','Ernstige corrosie',
 'Is ernstige corrosie aanwezig die de constructie aantast?',
 null,'nee','veiligheid','kritiek',
 'Er is geen constructie-aantastende corrosie aanwezig.',
 'Er is ernstige corrosie aangetroffen die de constructie van de balustrade aantast.',
 'Constructieve beoordeling laten uitvoeren en aangetast deel vervangen.',30),

('BAL-04','BAL','Lassen','Lasverbindingen',
 'Zijn de lasverbindingen gaaf en vrij van scheuren?',
 null,'ja','veiligheid','kritiek',
 'De lasverbindingen zijn gaaf.',
 'Er zijn scheuren of gebreken in lasverbindingen aangetroffen.',
 'Las laten beoordelen en opnieuw uitvoeren door een gekwalificeerde lasser.',40),

('BAL-05','BAL','Coating','Coating balustrade',
 'Is de coating intact?',
 null,'ja','technisch','esthetisch',
 'De coating van de balustrade is intact.',
 'De coating van de balustrade is niet intact.',
 'Coating bijwerken volgens het systeemvoorschrift.',50),

('BAL-06','BAL','Onderdelen','Losse onderdelen',
 'Zijn losse onderdelen aanwezig (spijlen, doppen, handgrepen)?',
 null,'nee','veiligheid','kritiek',
 'Er zijn geen losse onderdelen aan de balustrade.',
 'Er zijn losse onderdelen aan de balustrade aangetroffen.',
 'Onderdelen direct vastzetten of vervangen.',60),

-- ESTHETISCHE EINDKWALITEIT ---------------------------------------------------
('EST-01','EST','Kleur','Storend kleurverschil',
 'Is storend kleurverschil zichtbaar?',
 'Beoordeel op de gebruikelijke kijkafstand bij diffuus daglicht.','nee',
 'esthetisch','esthetisch',
 'Er is geen storend kleurverschil zichtbaar.',
 'Tussen gelijk voorgeschreven vlakken is een storend kleurverschil zichtbaar.',
 'Vlak in zijn geheel opnieuw afwerken.',10),

('EST-02','EST','Glans','Storend glansverschil',
 'Is storend glansverschil zichtbaar?',
 null,'nee','esthetisch','esthetisch',
 'Er is geen storend glansverschil zichtbaar.',
 'Tussen aansluitende gelijk afgewerkte vlakken is een storend glansverschil zichtbaar.',
 'Deelvlak opnieuw aflakken tot een natuurlijke stopplaats.',20),

('EST-03','EST','Reparaties','Reparatiebanen',
 'Zijn zichtbare reparatiebanen of reparatieovergangen aanwezig?',
 null,'nee','esthetisch','esthetisch',
 'Reparaties zijn niet als baan of overgang zichtbaar.',
 'Er zijn zichtbare reparatiebanen of reparatieovergangen aanwezig.',
 'Overgang uitvlakken en het deelvlak in een keer afwerken.',30),

('EST-04','EST','Lijnen','Aansluitlijnen',
 'Zijn scheve of onregelmatige aansluitlijnen aanwezig?',
 null,'nee','esthetisch','esthetisch',
 'Aansluitlijnen zijn recht en regelmatig.',
 'Er zijn scheve of onregelmatige aansluitlijnen aangetroffen.',
 'Lijn opnieuw uitzetten en afwerken.',40),

('EST-05','EST','Afwerking','Onafgewerkte plekken',
 'Zijn onafgewerkte plekken zichtbaar?',
 'Kijk expliciet achter regenpijpen, onder dorpels en op de bovenzijde van uitkragende delen.','nee',
 'esthetisch','esthetisch',
 'Er zijn geen onafgewerkte plekken zichtbaar.',
 'Er zijn onafgewerkte plekken aangetroffen.',
 'Plekken alsnog afwerken in het voorgeschreven systeem.',50),

('EST-06','EST','Netheid','Werkgerelateerde vervuiling',
 'Zijn werkgerelateerde vervuilingen zichtbaar?',
 null,'nee','esthetisch','esthetisch',
 'Er is geen werkgerelateerde vervuiling zichtbaar.',
 'Er is werkgerelateerde vervuiling aangetroffen op gereed werk.',
 'Vervuiling verwijderen zonder de afwerking te beschadigen.',60),

('EST-07','EST','Schilderwerk','Eindkwaliteit schilderwerk',
 'Is het schilderwerk vrij van zakkers, druipers, kale plekken, beschadigingen en grove schuurkrassen?',
 null,'ja','esthetisch','esthetisch',
 'Het schilderwerk voldoet aan het afgesproken esthetische eindniveau.',
 'Het schilderwerk voldoet op deze locatie niet aan het afgesproken esthetische eindniveau.',
 'Betrokken vlakken bijwerken en opnieuw aflakken.',70),

('EST-08','EST','Kitwerk','Eindkwaliteit kitwerk',
 'Is het kitwerk vrij van gaten, onderbrekingen, onthechting en vervuilde kanten?',
 null,'ja','esthetisch','esthetisch',
 'Het kitwerk voldoet aan het afgesproken esthetische eindniveau.',
 'Het kitwerk voldoet op deze locatie niet aan het afgesproken esthetische eindniveau.',
 'Voeg bijwerken en kanten reinigen.',80),

('EST-09','EST','Voegwerk','Eindkwaliteit voegwerk',
 'Komt het voegwerk in kleur, profiel, structuur en regelmaat overeen met het referentievlak?',
 null,'ja','esthetisch','esthetisch',
 'Het voegwerk komt overeen met het referentievlak.',
 'Het voegwerk wijkt in kleur, profiel, structuur of regelmaat af van het referentievlak.',
 'Afwijkend vlak uithakken en opnieuw voegen.',90),

('EST-10','EST','Oplevering','Schoon opleveren',
 'Is het werkgebied schoon opgeleverd, zonder verf, kit, mortel, tape, folie, stickers of afval?',
 null,'ja','esthetisch','esthetisch',
 'Het werkgebied is schoon opgeleverd.',
 'Het werkgebied is niet schoon opgeleverd; er zijn resten van verf, kit, mortel, tape, folie, stickers of afval aangetroffen.',
 'Werkgebied opruimen en reinigen voordat het als gereed wordt gemeld.',100)

on conflict (code) do nothing;

-- ── B. Controlepunten met een meting ─────────────────────────────────────────
-- Grenswaarden staan op INTERN; zie de kop van dit bestand.
insert into public.kwaliteit_controlepunten
  (code, discipline_code, component, titel, korte_vraag, toelichting, inspectie_type,
   kwaliteitsaspect, standaard_ernst, meting_verplicht, meting_optioneel, meetmethode, meetmiddel,
   eenheid, min_waarde, max_waarde, doel_waarde, tolerantie_min, tolerantie_plus,
   project_eis_sleutel, bron_type, bron_document, eis_tekst, rapport_tekst_voldoet_niet,
   standaard_herstelactie, volgorde)
values

('SCH-01','SCH','Houten ondergrond','Houtvocht',
 'Meet het houtvocht op een representatieve of verdachte locatie.',
 'Meet bij voorkeur op de onderdorpel en op plekken met vochtbelasting. Is het hout al volledig afgeschilderd en de waarde niet meer zinvol te controleren, kies dan NIET BEOORDEELD in plaats van een meting te forceren.',
 'meting','technisch','technisch', false, true,
 'Meting met een penmeter op ten minste drie punten per element; noteer de hoogste waarde.',
 'houtvochtmeter','%', null, 18, null, null, null,
 null,'INTERN','Bedrijfsnorm, ontleend aan BRL 5026',
 'Het houtvochtgehalte bedraagt maximaal 18%. Daarnaast is het verschil binnen hetzelfde element maximaal 4 procentpunt.',
 'Het gemeten houtvocht overschrijdt de maximale grenswaarde. Het onderdeel voldoet niet aan het technische kwaliteitscriterium.',
 'Oorzaak van de vochtbelasting vaststellen en het onderdeel niet verder afwerken totdat het houtvocht aan de eis voldoet.',10),

('SCH-05','SCH','Verflaag','Verfhechting',
 'Is verfonthechting zichtbaar, en wat is de uitkomst van een eventuele hechtingstest?',
 'Visuele onthechting is nooit toegestaan. Voer je een ruitjesproef uit, vul dan de classificatie 0 t/m 5 in: 0 t/m 3 voldoet, 4 en 5 voldoen niet.',
 'gecombineerd','technisch','technisch', false, true,
 'Ruitjesproef volgens de systematiek van het toegepaste verfsysteem; classificatie 0 t/m 5.',
 'hechtingstestset','klasse', null, 3, null, null, null,
 null,'INTERN','Bedrijfsnorm, ontleend aan de SKH/BRL-systematiek voor hechting',
 'Er is geen zichtbare onthechting. Bij een uitgevoerde hechtingstest is klasse 0 t/m 3 toegestaan.',
 'De hechting van de verflaag voldoet niet aan het kwaliteitscriterium.',
 'Losse lagen verwijderen, ondergrond voorbehandelen en het systeem opnieuw opbouwen.',50),

('SCH-10','SCH','Kleur','Kleurbeeld',
 'Is een zichtbaar afwijkend kleurbeeld aanwezig tussen gelijk voorgeschreven vlakken?',
 'Beoordeel visueel op de gebruikelijke kijkafstand. Alleen bij twijfel en als het project een kleurtolerantie voorschrijft een instrumentele meting doen; er is bewust geen generieke tolerantie vastgelegd.',
 'gecombineerd','esthetisch','esthetisch', false, true,
 'Instrumentele kleurmeting op ten minste drie punten per vlak, vergeleken met het referentievlak.',
 'colorimeter','dE', null, null, null, null, null,
 'kleurtolerantie','PROJECT','Projectspecificatie of productblad',
 'Tussen gelijk voorgeschreven vlakken is geen zichtbaar kleurverschil aanwezig. Een numerieke tolerantie geldt alleen als het project die voorschrijft.',
 'Tussen gelijk voorgeschreven vlakken is een afwijkend kleurbeeld geconstateerd.',
 'Vlak in zijn geheel opnieuw afwerken met gecontroleerde menging.',100),

('SCH-11','SCH','Glans','Glansbeeld',
 'Is een storend glansverschil zichtbaar tussen gelijk afgewerkte aansluitende vlakken?',
 'Optionele glansmeting alleen wanneer het project of het productblad een glanswaarde voorschrijft.',
 'gecombineerd','esthetisch','esthetisch', false, true,
 'Glansmeting onder de in het productblad voorgeschreven hoek, op ten minste drie punten.',
 'glansmeter','GU', null, null, null, null, null,
 'glanswaarde','PROJECT','Projectspecificatie of productblad',
 'Tussen gelijk afgewerkte aansluitende vlakken is geen storend glansverschil aanwezig.',
 'Tussen gelijk afgewerkte aansluitende vlakken is een storend glansverschil geconstateerd.',
 'Deelvlak opnieuw aflakken tot een natuurlijke stopplaats.',110),

('HHR-02','HHR','Ondergrond','Houtvocht bij herstel',
 'Meet het houtvocht bij de reparatie, als dat nog betrouwbaar mogelijk is.',
 'Alleen zinvol zolang het reparatievlak nog niet volledig is afgewerkt.',
 'meting','technisch','technisch', false, true,
 'Meting met een penmeter naast en in het reparatievlak.',
 'houtvochtmeter','%', null, 18, null, null, null,
 null,'INTERN','Bedrijfsnorm, ontleend aan BRL 5026',
 'Het houtvochtgehalte ter plaatse van de reparatie bedraagt maximaal 18%.',
 'Het gemeten houtvocht bij de reparatie overschrijdt de maximale grenswaarde.',
 'Reparatie niet verder afwerken totdat het houtvocht aan de eis voldoet; oorzaak van de vochtbelasting wegnemen.',20),

('HHR-06','HHR','Vlakheid','Vlakheid reparatievlak',
 'Is een storende verhoging of verdieping in het reparatievlak zichtbaar?',
 'Bij twijfel meten met een rei: leg de rei over de reparatie en meet de grootste afwijking.',
 'gecombineerd','esthetisch','esthetisch', false, true,
 'Rei over het reparatievlak leggen en de grootste afwijking meten met een voelermaat.',
 'rei 1 m','mm', null, null, null, null, null,
 'vlakheid_hout','PROJECT','Projectspecificatie of uitvoeringsafspraak',
 'Het reparatievlak sluit vlak aan op het omliggende hout. Een numerieke tolerantie geldt alleen als het project die voorschrijft.',
 'In het reparatievlak is een storende verhoging of verdieping aanwezig.',
 'Vlak bijwerken tot het vlak aansluit en opnieuw afwerken.',60),

('KOZ-03','KOZ','Draaiend deel','Hangnaad',
 'Meet de hangnaad van het geselecteerde draaiende deel.',
 'Alleen invullen bij een houten draaiend deel waarvoor deze maat geldt. Bij een ander systeem: N.V.T.',
 'meting','functioneel','technisch', false, true,
 'Voelermaat op drie punten langs de hangzijde; noteer de grootste afwijking.',
 'voelermaat','mm', null, null, 2, 1, 1,
 'hangnaad','INTERN','Bedrijfsnorm voor houten draaiende delen',
 'De hangnaad bedraagt 2 mm met een tolerantie van 1 mm.',
 'De gemeten hangnaad valt buiten de toegestane tolerantie.',
 'Draaiend deel afstellen of bijwerken tot de naad binnen de tolerantie valt.',30),

('KOZ-04','KOZ','Draaiend deel','Sluitnaad',
 'Meet de sluitnaad van het geselecteerde draaiende deel.',
 'Alleen invullen bij een naar buiten draaiend houten deel waarvoor deze maat geldt. Bij een ander systeem: N.V.T.',
 'meting','functioneel','technisch', false, true,
 'Voelermaat op drie punten langs de sluitzijde; noteer de grootste afwijking.',
 'voelermaat','mm', null, null, 3, 1, 1,
 'sluitnaad','INTERN','Bedrijfsnorm voor naar buiten draaiende houten delen',
 'De sluitnaad bedraagt 3 mm met een tolerantie van 1 mm.',
 'De gemeten sluitnaad valt buiten de toegestane tolerantie.',
 'Draaiend deel afstellen tot de naad binnen de tolerantie valt.',40),

('GL-04','GL','Sponning','Omtrekspeling',
 'Meet de omtrekspeling, als het detail tijdens de werkzaamheden controleerbaar is.',
 'Alleen invullen wanneer de sponning open ligt. De minimumwaarde is detailafhankelijk; is er een projectwaarde, dan gaat die voor.',
 'meting','technisch','technisch', false, true,
 'Schuifmaat in de sponning, aan alle vier de zijden.',
 'schuifmaat','mm', 5, null, null, null, null,
 'omtrekspeling','INTERN','Bedrijfsnorm, ontleend aan de NPR 3577-detaillering',
 'De omtrekspeling bedraagt ten minste 5 mm, tenzij het toegepaste detail een andere waarde voorschrijft.',
 'De gemeten omtrekspeling is kleiner dan de vereiste minimumwaarde.',
 'Sponning aanpassen of de ruitmaat corrigeren volgens het toepasselijke detail.',40),

('GL-05','GL','Sponning','Sponninghoogte',
 'Meet de sponninghoogte, als het detail controleerbaar is.',
 'Detailafhankelijk; is er een projectwaarde, dan gaat die voor.',
 'meting','technisch','technisch', false, true,
 'Schuifmaat van sponningbodem tot bovenkant sponningrand.',
 'schuifmaat','mm', 17, null, null, null, null,
 'sponninghoogte','INTERN','Bedrijfsnorm, ontleend aan de NPR 3577-detaillering',
 'De sponninghoogte bedraagt ten minste 17 mm, tenzij het toegepaste detail een andere waarde voorschrijft.',
 'De gemeten sponninghoogte is kleiner dan de vereiste minimumwaarde.',
 'Detail aanpassen volgens het toepasselijke beglazingssysteem.',50),

('GL-06','GL','Afdichting','Topafdichting',
 'Meet de topafdichting, als het detail controleerbaar is.',
 'Systeemafhankelijk. Vul de gemeten hoogte in; leg de projectwaarde vast bij de projecteisen.',
 'meting','technisch','technisch', false, true,
 'Schuifmaat op de topafdichting, op drie punten per zijde.',
 'schuifmaat','mm', 4, null, null, null, null,
 'topafdichting','INTERN','Bedrijfsnorm, ontleend aan de gangbare beglazingsdetaillering',
 'De topafdichting bedraagt ten minste circa 4 bij 6 mm, tenzij het toegepaste systeem een andere maat voorschrijft.',
 'De gemeten topafdichting is kleiner dan de vereiste minimumwaarde.',
 'Afdichting aanvullen volgens het systeemvoorschrift.',60),

('GL-08','GL','Glaslat','Bevestigingsafstand glaslat',
 'Meet de hart-op-hart afstand van de glaslatbevestiging, als het detail zichtbaar en relevant is.',
 'De toegestane afstand verschilt per bevestigingsmiddel en per detail. Er is bewust geen enkele generieke waarde vastgelegd; leg de projectwaarde vast bij de projecteisen.',
 'meting','technisch','technisch', false, true,
 'Rolmaat tussen twee opeenvolgende bevestigingen; noteer de grootste afstand.',
 'rolmaat','mm', null, null, null, null, null,
 'glaslat_bevestigingsafstand','PROJECT','Projectspecificatie of systeemdetail',
 'De bevestigingsafstand van de glaslat volgt het toegepaste detail. Voor dit project is geen generieke waarde beschikbaar; stel de projecteis in.',
 'De gemeten bevestigingsafstand van de glaslat voldoet niet aan de projecteis.',
 'Extra bevestiging aanbrengen volgens het toepasselijke detail.',80),

('KIT-03','KIT','Voeg','Voegbreedte',
 'Meet de voegbreedte, als die nog te meten is.',
 'De minimale breedte hangt af van het kitsysteem (elastisch, plastisch-elastisch of plastisch). Leg het gekozen systeem en de bijbehorende minimumbreedte vast bij de projecteisen.',
 'meting','technisch','technisch', false, true,
 'Schuifmaat op drie punten per voeg; noteer de kleinste waarde.',
 'schuifmaat','mm', null, null, null, null, null,
 'voegbreedte','PROJECT','Projectspecificatie op basis van het gekozen kitsysteem',
 'De voegbreedte voldoet aan de minimale breedte van het gekozen kitsysteem. Voor dit project is geen generieke waarde beschikbaar; stel de projecteis in.',
 'De gemeten voegbreedte is kleiner dan de minimale breedte van het gekozen kitsysteem.',
 'Voeg verbreden of het kitsysteem heroverwegen in overleg met de leverancier.',30),

('KIT-04','KIT','Voeg','Voegdiepte',
 'Meet de voegdiepte, als die technisch nog meetbaar is.',
 'De vereiste diepte volgt uit de voegbreedte en het kitsysteem. Leg de projectwaarde vast bij de projecteisen.',
 'meting','technisch','technisch', false, true,
 'Dieptemaat van de schuifmaat, op drie punten per voeg.',
 'schuifmaat','mm', null, null, null, null, null,
 'voegdiepte','PROJECT','Projectspecificatie op basis van het gekozen kitsysteem',
 'De voegdiepte voldoet aan de verhouding die het gekozen kitsysteem voorschrijft. Voor dit project is geen generieke waarde beschikbaar; stel de projecteis in.',
 'De gemeten voegdiepte voldoet niet aan de projecteis.',
 'Voeg opnieuw opbouwen met de juiste rugvulling en diepte.',40),

('KIT-07','KIT','Condities','Applicatietemperatuur',
 'Meet de object- en omgevingstemperatuur, als er tijdens de inspectie wordt gekit.',
 'Alleen invullen wanneer er op dat moment daadwerkelijk wordt gekit. De productspecificatie van de fabrikant gaat altijd voor op de bedrijfsnorm.',
 'meting','technisch','technisch', false, true,
 'Oppervlaktethermometer op het object en thermometer voor de omgevingstemperatuur.',
 'oppervlaktethermometer','C', 5, 30, null, null, null,
 'kit_applicatietemperatuur','INTERN','Bedrijfsnorm; productspecificatie fabrikant gaat voor',
 'Object- en omgevingstemperatuur liggen tussen 5 en 30 graden Celsius, tenzij het productblad anders voorschrijft.',
 'De gemeten temperatuur valt buiten het toegestane bereik voor applicatie.',
 'Kitwerk stilleggen tot de condities binnen het toegestane bereik vallen.',70),

('MW-02','MW','Scheur','Scheurwijdte',
 'Meet de maximale scheurwijdte en leg lengte en richting van de scheur vast.',
 'Fotografeer de scheur met de scheurwijdtemeter ernaast en noteer lengte en richting in de toelichting.',
 'meting','technisch','technisch', false, true,
 'Scheurwijdtemeter op het breedste punt van de scheur.',
 'scheurwijdtemeter','mm', null, null, null, null, null,
 'scheurwijdte','PROJECT','Projectspecificatie of constructieve beoordeling',
 'De toelaatbare scheurwijdte volgt uit de projectspecificatie of een constructieve beoordeling. Er is bewust geen generieke waarde vastgelegd.',
 'De gemeten scheurwijdte overschrijdt de vastgelegde projecteis.',
 'Scheur laten beoordelen en herstellen volgens het vastgestelde herstelvoorstel.',20),

('MW-07','MW','Vlakheid','Vlakheid metselwerk',
 'Meet bij twijfel de vlakheid van het metselwerk met een rei.',
 'Alleen invullen bij zichtbare onvlakheid. De toegestane afwijking komt uit het bestek of de uitvoeringsspecificatie.',
 'meting','esthetisch','esthetisch', false, true,
 'Rei van 2 meter tegen het vlak; grootste opening meten met een voelermaat.',
 'rei 2 m','mm', null, null, null, null, null,
 'vlakheid_metselwerk','PROJECT','Bestek of uitvoeringsspecificatie',
 'De vlakheid voldoet aan de tolerantie uit het bestek of de uitvoeringsspecificatie. Er is bewust geen generieke waarde vastgelegd.',
 'De gemeten vlakheid van het metselwerk voldoet niet aan de projecteis.',
 'Vlak herstellen binnen de gestelde tolerantie.',70),

('VW-04','VW','Voegwerk','Voegdiepte',
 'Meet de voegdiepte waar dat relevant en mogelijk is.',
 'De voorgeschreven diepte komt uit het bestek of de gekozen voegrichtlijn.',
 'meting','technisch','technisch', false, true,
 'Dieptemaat van de schuifmaat op drie punten per vlak.',
 'schuifmaat','mm', null, null, null, null, null,
 'voegwerk_diepte','PROJECT','Bestek of gekozen voegrichtlijn',
 'De voegdiepte voldoet aan de projectspecificatie. Er is bewust geen generieke waarde vastgelegd.',
 'De gemeten voegdiepte voldoet niet aan de projecteis.',
 'Voegwerk uithakken en op de juiste diepte opnieuw voegen.',40),

('GC-02','GC','Condities','Ondergrondvocht',
 'Meet het vochtgehalte van de ondergrond, als het coatingsysteem daar een eis aan stelt.',
 'De grenswaarde komt uit het productblad van het gekozen coatingsysteem; leg die vast bij de projecteisen.',
 'meting','technisch','technisch', false, true,
 'Vochtmeting op de ondergrond op ten minste drie punten per vlak.',
 'vochtmeter','%', null, null, null, null, null,
 'coating_ondergrondvocht','FABRIKANT','Productblad van het gekozen coatingsysteem',
 'Het vochtgehalte van de ondergrond voldoet aan de eis uit het productblad. Er is bewust geen generieke waarde vastgelegd; stel de projecteis in.',
 'Het gemeten ondergrondvocht voldoet niet aan de eis van het coatingsysteem.',
 'Coaten uitstellen tot de ondergrond voldoende droog is.',20),

('GC-03','GC','Condities','Luchttemperatuur',
 'Meet de luchttemperatuur.',
 'De toegestane ondergrens komt uit het productblad; leg die vast bij de projecteisen.',
 'meting','technisch','technisch', false, true,
 'Thermometer in de schaduw, op werkhoogte.',
 'thermometer','C', null, null, null, null, null,
 'coating_luchttemperatuur','FABRIKANT','Productblad van het gekozen coatingsysteem',
 'De luchttemperatuur voldoet aan het bereik uit het productblad. Er is bewust geen generieke waarde vastgelegd; stel de projecteis in.',
 'De gemeten luchttemperatuur valt buiten het toegestane bereik van het coatingsysteem.',
 'Werkzaamheden stilleggen tot de condities binnen het bereik vallen.',30),

('GC-04','GC','Condities','Ondergrondtemperatuur',
 'Meet de temperatuur van de ondergrond.',
 'De toegestane ondergrens komt uit het productblad; leg die vast bij de projecteisen.',
 'meting','technisch','technisch', false, true,
 'Oppervlaktethermometer op de te coaten ondergrond.',
 'oppervlaktethermometer','C', null, null, null, null, null,
 'coating_ondergrondtemperatuur','FABRIKANT','Productblad van het gekozen coatingsysteem',
 'De ondergrondtemperatuur voldoet aan het bereik uit het productblad. Er is bewust geen generieke waarde vastgelegd; stel de projecteis in.',
 'De gemeten ondergrondtemperatuur valt buiten het toegestane bereik van het coatingsysteem.',
 'Werkzaamheden stilleggen tot de condities binnen het bereik vallen.',40),

('GC-05','GC','Condities','Relatieve luchtvochtigheid',
 'Meet de relatieve luchtvochtigheid.',
 'De toegestane bovengrens komt uit het productblad; leg die vast bij de projecteisen.',
 'meting','technisch','technisch', false, true,
 'Hygrometer op werkhoogte, uit de directe zon.',
 'hygrometer','%', null, null, null, null, null,
 'coating_rv','FABRIKANT','Productblad van het gekozen coatingsysteem',
 'De relatieve luchtvochtigheid voldoet aan de eis uit het productblad. Er is bewust geen generieke waarde vastgelegd; stel de projecteis in.',
 'De gemeten relatieve luchtvochtigheid valt buiten het toegestane bereik van het coatingsysteem.',
 'Werkzaamheden stilleggen tot de condities binnen het bereik vallen.',50),

('GC-06','GC','Condities','Dauwpuntverschil',
 'Meet het verschil tussen ondergrondtemperatuur en dauwpunt, als het systeem dat vereist.',
 'Vul het verschil in graden in. De minimale marge komt uit het productblad.',
 'meting','technisch','technisch', false, true,
 'Dauwpunt bepalen uit luchttemperatuur en relatieve luchtvochtigheid; verschil met de ondergrondtemperatuur berekenen.',
 'hygrometer','C', null, null, null, null, null,
 'coating_dauwpuntmarge','FABRIKANT','Productblad van het gekozen coatingsysteem',
 'Het verschil tussen ondergrondtemperatuur en dauwpunt voldoet aan de marge uit het productblad. Er is bewust geen generieke waarde vastgelegd; stel de projecteis in.',
 'De gemeten dauwpuntmarge voldoet niet aan de eis van het coatingsysteem.',
 'Werkzaamheden stilleggen tot de dauwpuntmarge voldoende is.',60),

('GC-13','GC','Laagdikte','Laagdikte coating',
 'Meet de laagdikte, als het systeem daar een eis aan stelt.',
 'De voorgeschreven laagdikte komt uit het productblad; leg die vast bij de projecteisen.',
 'meting','technisch','technisch', false, true,
 'Laagdiktemeting op ten minste vijf punten per vlak; noteer het gemiddelde.',
 'laagdiktemeter','um', null, null, null, null, null,
 'coating_laagdikte','FABRIKANT','Productblad van het gekozen coatingsysteem',
 'De laagdikte voldoet aan de waarde uit het productblad. Er is bewust geen generieke waarde vastgelegd; stel de projecteis in.',
 'De gemeten laagdikte voldoet niet aan de systeemeis.',
 'Extra laag aanbrengen tot de voorgeschreven laagdikte is bereikt.',130),

('BET-02','BET','Scheur','Scheurregistratie beton',
 'Meet de maximale scheurwijdte in het beton en leg lengte en richting vast.',
 'Bij een onverklaarde of actieve scheur hoort NADER ONDERZOEK, niet VOLDOET NIET.',
 'meting','technisch','technisch', false, true,
 'Scheurwijdtemeter op het breedste punt; lengte en richting noteren.',
 'scheurwijdtemeter','mm', null, null, null, null, null,
 'beton_scheurwijdte','PROJECT','Constructieve beoordeling of bestek',
 'De toelaatbare scheurwijdte volgt uit de constructieve beoordeling of het bestek. Er is bewust geen generieke waarde vastgelegd.',
 'De gemeten scheurwijdte overschrijdt de vastgelegde projecteis.',
 'Scheur constructief laten beoordelen en herstellen volgens het vastgestelde voorstel.',20),

('BET-06','BET','Beproeving','Trekproef betonherstel',
 'Voer een trekproef uit wanneer die contractueel of systeemtechnisch is vereist, en vul de gemeten hechtsterkte in.',
 'Nooit zelf een grenswaarde aannemen: die komt uit het NEN-EN 1504-systeem, het productblad of het bestek.',
 'meting','technisch','technisch', false, true,
 'Trekproef volgens het voorschrift van het toegepaste herstelsysteem.',
 'trekproefapparatuur','MPa', null, null, null, null, null,
 'beton_hechtsterkte','PROJECT','NEN-EN 1504-systeem, productblad of bestek',
 'De hechtsterkte voldoet aan de waarde uit het toegepaste herstelsysteem. Er is bewust geen generieke waarde vastgelegd; stel de projecteis in.',
 'De gemeten hechtsterkte voldoet niet aan de systeemeis.',
 'Herstelvlak verwijderen en opnieuw uitvoeren; uitvoeringsmethode evalueren.',60),

('BET-08','BET','Vlakheid','Vlakheid betonherstel',
 'Meet de vlakheid van het herstelvlak bij twijfel.',
 null,
 'meting','esthetisch','esthetisch', false, true,
 'Rei van 2 meter over het herstelvlak; grootste opening meten met een voelermaat.',
 'rei 2 m','mm', null, null, null, null, null,
 'vlakheid_beton','PROJECT','Bestek of uitvoeringsspecificatie',
 'De vlakheid voldoet aan de tolerantie uit het bestek. Er is bewust geen generieke waarde vastgelegd.',
 'De gemeten vlakheid van het herstelvlak voldoet niet aan de projecteis.',
 'Vlak bijwerken binnen de gestelde tolerantie.',80),

('STU-03','STU','Vlakheid','Vlakheid stucwerk',
 'Meet de vlakheid van het stucwerk bij twijfel.',
 null,
 'meting','esthetisch','esthetisch', false, true,
 'Rei van 2 meter tegen het vlak; grootste opening meten met een voelermaat.',
 'rei 2 m','mm', null, null, null, null, null,
 'vlakheid_stuc','PROJECT','Bestek of uitvoeringsspecificatie',
 'De vlakheid voldoet aan de tolerantie uit het bestek. Er is bewust geen generieke waarde vastgelegd.',
 'De gemeten vlakheid van het stucwerk voldoet niet aan de projecteis.',
 'Vlak bijwerken binnen de gestelde tolerantie.',30),

('MET-04','MET','Laagdikte','Laagdikte conservering',
 'Meet de laagdikte van de conservering waar die is voorgeschreven.',
 'De voorgeschreven laagdikte komt uit het conserveringssysteem; leg die vast bij de projecteisen.',
 'meting','technisch','technisch', false, true,
 'Laagdiktemeting op ten minste vijf punten per element; noteer het gemiddelde en de laagste waarde.',
 'laagdiktemeter','um', null, null, null, null, null,
 'metaal_laagdikte','FABRIKANT','Productblad van het toegepaste conserveringssysteem',
 'De laagdikte voldoet aan de waarde uit het conserveringssysteem. Er is bewust geen generieke waarde vastgelegd; stel de projecteis in.',
 'De gemeten laagdikte voldoet niet aan de systeemeis.',
 'Extra laag aanbrengen tot de voorgeschreven laagdikte is bereikt.',40)

on conflict (code) do nothing;

-- ── C. Functionele en documentcontroles ──────────────────────────────────────
insert into public.kwaliteit_controlepunten
  (code, discipline_code, component, titel, korte_vraag, toelichting, inspectie_type,
   kwaliteitsaspect, standaard_ernst, binair_voldoet_bij, eis_tekst, rapport_tekst_voldoet_niet,
   standaard_herstelactie, volgorde)
values

('KOZ-01','KOZ','Draaiend deel','Functioneren draaiend deel',
 'Open, sluit, vergrendel en ontgrendel het geselecteerde draaiende deel: werkt alles?',
 'Voer alle vier de handelingen daadwerkelijk uit; een deel dat sluit maar niet vergrendelt voldoet niet.',
 'functioneel','functioneel','technisch','ja',
 'Het draaiende deel is te openen, te sluiten, te vergrendelen en te ontgrendelen zonder overmatige kracht.',
 'Het draaiende deel functioneert niet volledig: openen, sluiten, vergrendelen of ontgrendelen verloopt niet naar behoren.',
 'Deel afstellen en het hang- en sluitwerk nalopen tot alle vier de handelingen werken.',10),

('MW-03','MW','Scheur','Onverklaarde scheur',
 'Is de scheur onverklaard of mogelijk actief?',
 'Bij twijfel over de oorzaak hoort NADER ONDERZOEK: een constructieve scheur beoordeel je niet op het oog.',
 'visueel','technisch','kritiek','nee',
 'Elke scheur is verklaard en aantoonbaar niet actief.',
 'Er is een onverklaarde of mogelijk actieve scheur aangetroffen. Beoordeling door een specialist is noodzakelijk.',
 'Constructieve beoordeling laten uitvoeren voordat wordt hersteld.',30),

('VW-05','VW','Profiel','Voegprofiel',
 'Komt het uitgevoerde voegprofiel overeen met het voorgeschreven profiel?',
 'Voorgeschreven profielen: platvol, verdiept, doorgestreken, geknipt, gesneden of anders. Noteer het aangetroffen profiel in de toelichting.',
 'visueel','esthetisch','esthetisch','ja',
 'Het uitgevoerde voegprofiel komt overeen met het voorgeschreven profiel.',
 'Het uitgevoerde voegprofiel wijkt af van het voorgeschreven profiel.',
 'Afwijkend vlak uithakken en opnieuw voegen in het juiste profiel.',50),

('HWA-03','HWA','Beproeving','Waterproef hemelwaterafvoer',
 'Is een waterproef uitgevoerd waar daar aanleiding toe was, en was het resultaat lekvrij?',
 'Voer de waterproef uit bij vermoeden van lekkage of na herstelwerk aan de afvoer. Is er geen aanleiding, kies dan N.V.T.',
 'functioneel','functioneel','technisch','ja',
 'De uitgevoerde waterproef toont een lekvrije hemelwaterafvoer.',
 'De waterproef toont een lekkage in de hemelwaterafvoer.',
 'Lekkage lokaliseren en de verbinding of het onderdeel herstellen.',30)

on conflict (code) do nothing;

-- ── Controle op de omvang ────────────────────────────────────────────────────
-- 167 controlepunten verdeeld over 22 disciplines. Wijkt het aantal af, dan is een insert
-- afgeketst op een dubbele code.
do $check$
declare
  aantal integer;
begin
  select count(*) into aantal from public.kwaliteit_controlepunten;
  raise notice 'Kwaliteitsbibliotheek bevat nu % controlepunten.', aantal;
end $check$;
